/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "archiveitem.h"


Nepomuk::ArchiveItem::ArchiveItem()
  : EmbeddedFileDataObject( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem") )
{
}


Nepomuk::ArchiveItem::ArchiveItem( const ArchiveItem& res )
  : EmbeddedFileDataObject( res )
{
}


Nepomuk::ArchiveItem::ArchiveItem( const Nepomuk::Resource& res )
  : EmbeddedFileDataObject( res )
{
}


Nepomuk::ArchiveItem::ArchiveItem( const QString& uri )
  : EmbeddedFileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem") )
{
}

Nepomuk::ArchiveItem::ArchiveItem( const QUrl& uri )
  : EmbeddedFileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem") )
{
}

Nepomuk::ArchiveItem::ArchiveItem( const QString& uri, const QUrl& type )
  : EmbeddedFileDataObject( uri, type )
{
}

Nepomuk::ArchiveItem::ArchiveItem( const QUrl& uri, const QUrl& type )
  : EmbeddedFileDataObject( uri, type )
{
}

Nepomuk::ArchiveItem::~ArchiveItem()
{
}


Nepomuk::ArchiveItem& Nepomuk::ArchiveItem::operator=( const ArchiveItem& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::ArchiveItem::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem";
}

QList<bool> Nepomuk::ArchiveItem::isPasswordProtecteds() const
{
    return ( property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected") ).toBoolList());
}

void Nepomuk::ArchiveItem::setIsPasswordProtecteds( const QList<bool>& value )
{
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected"), Variant( value ) );
}

void Nepomuk::ArchiveItem::addIsPasswordProtected( const bool& value )
{
    Variant v = property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected") );
    v.append( value );
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected"), v );
}

QUrl Nepomuk::ArchiveItem::isPasswordProtectedUri()
{
    return QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected");
}

QList<Nepomuk::ArchiveItem> Nepomuk::ArchiveItem::allArchiveItems()
{
    return Nepomuk::convertResourceList<ArchiveItem>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem") ) );
}


