/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "attachment.h"

#include "message.h"
Nepomuk::Attachment::Attachment()
  : EmbeddedFileDataObject( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Attachment") )
{
}


Nepomuk::Attachment::Attachment( const Attachment& res )
  : EmbeddedFileDataObject( res )
{
}


Nepomuk::Attachment::Attachment( const Nepomuk::Resource& res )
  : EmbeddedFileDataObject( res )
{
}


Nepomuk::Attachment::Attachment( const QString& uri )
  : EmbeddedFileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Attachment") )
{
}

Nepomuk::Attachment::Attachment( const QUrl& uri )
  : EmbeddedFileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Attachment") )
{
}

Nepomuk::Attachment::Attachment( const QString& uri, const QUrl& type )
  : EmbeddedFileDataObject( uri, type )
{
}

Nepomuk::Attachment::Attachment( const QUrl& uri, const QUrl& type )
  : EmbeddedFileDataObject( uri, type )
{
}

Nepomuk::Attachment::~Attachment()
{
}


Nepomuk::Attachment& Nepomuk::Attachment::operator=( const Attachment& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::Attachment::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Attachment";
}

QList<Nepomuk::Message> Nepomuk::Attachment::attachmentOf() const
{
    return convertResourceList<Message>( ResourceManager::instance()->allResourcesWithProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#hasAttachment"), *this ) );
}

QList<Nepomuk::Attachment> Nepomuk::Attachment::allAttachments()
{
    return Nepomuk::convertResourceList<Attachment>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Attachment") ) );
}


