/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "audioimaccount.h"


Nepomuk::AudioIMAccount::AudioIMAccount()
  : IMAccount( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount") )
{
}


Nepomuk::AudioIMAccount::AudioIMAccount( const AudioIMAccount& res )
  : IMAccount( res )
{
}


Nepomuk::AudioIMAccount::AudioIMAccount( const Nepomuk::Resource& res )
  : IMAccount( res )
{
}


Nepomuk::AudioIMAccount::AudioIMAccount( const QString& uri )
  : IMAccount( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount") )
{
}

Nepomuk::AudioIMAccount::AudioIMAccount( const QUrl& uri )
  : IMAccount( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount") )
{
}

Nepomuk::AudioIMAccount::AudioIMAccount( const QString& uri, const QUrl& type )
  : IMAccount( uri, type )
{
}

Nepomuk::AudioIMAccount::AudioIMAccount( const QUrl& uri, const QUrl& type )
  : IMAccount( uri, type )
{
}

Nepomuk::AudioIMAccount::~AudioIMAccount()
{
}


Nepomuk::AudioIMAccount& Nepomuk::AudioIMAccount::operator=( const AudioIMAccount& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::AudioIMAccount::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount";
}

QList<Nepomuk::AudioIMAccount> Nepomuk::AudioIMAccount::allAudioIMAccounts()
{
    return Nepomuk::convertResourceList<AudioIMAccount>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount") ) );
}


