/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "compressiontype.h"

#include "media.h"
Nepomuk::CompressionType::CompressionType()
  : Resource( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#CompressionType") )
{
}


Nepomuk::CompressionType::CompressionType( const CompressionType& res )
  : Resource( res )
{
}


Nepomuk::CompressionType::CompressionType( const Nepomuk::Resource& res )
  : Resource( res )
{
}


Nepomuk::CompressionType::CompressionType( const QString& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#CompressionType") )
{
}

Nepomuk::CompressionType::CompressionType( const QUrl& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#CompressionType") )
{
}

Nepomuk::CompressionType::CompressionType( const QString& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk::CompressionType::CompressionType( const QUrl& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk::CompressionType::~CompressionType()
{
}


Nepomuk::CompressionType& Nepomuk::CompressionType::operator=( const CompressionType& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::CompressionType::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#CompressionType";
}

QList<Nepomuk::Media> Nepomuk::CompressionType::compressionTypeOf() const
{
    return convertResourceList<Media>( ResourceManager::instance()->allResourcesWithProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#compressionType"), *this ) );
}

QList<Nepomuk::CompressionType> Nepomuk::CompressionType::allCompressionTypes()
{
    return Nepomuk::convertResourceList<CompressionType>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#CompressionType") ) );
}


