/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "contactlistdataobject.h"

#include "contactlist.h"
Nepomuk::ContactListDataObject::ContactListDataObject()
  : DataObject( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactListDataObject") )
{
}


Nepomuk::ContactListDataObject::ContactListDataObject( const ContactListDataObject& res )
  : DataObject( res )
{
}


Nepomuk::ContactListDataObject::ContactListDataObject( const Nepomuk::Resource& res )
  : DataObject( res )
{
}


Nepomuk::ContactListDataObject::ContactListDataObject( const QString& uri )
  : DataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactListDataObject") )
{
}

Nepomuk::ContactListDataObject::ContactListDataObject( const QUrl& uri )
  : DataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactListDataObject") )
{
}

Nepomuk::ContactListDataObject::ContactListDataObject( const QString& uri, const QUrl& type )
  : DataObject( uri, type )
{
}

Nepomuk::ContactListDataObject::ContactListDataObject( const QUrl& uri, const QUrl& type )
  : DataObject( uri, type )
{
}

Nepomuk::ContactListDataObject::~ContactListDataObject()
{
}


Nepomuk::ContactListDataObject& Nepomuk::ContactListDataObject::operator=( const ContactListDataObject& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::ContactListDataObject::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactListDataObject";
}

QList<Nepomuk::ContactList> Nepomuk::ContactListDataObject::containsContactOf() const
{
    return convertResourceList<ContactList>( ResourceManager::instance()->allResourcesWithProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#containsContact"), *this ) );
}

QList<Nepomuk::ContactListDataObject> Nepomuk::ContactListDataObject::allContactListDataObjects()
{
    return Nepomuk::convertResourceList<ContactListDataObject>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactListDataObject") ) );
}


