/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "contactlist.h"

#include "contactlistdataobject.h"
Nepomuk::ContactList::ContactList()
  : InformationElement( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactList") )
{
}


Nepomuk::ContactList::ContactList( const ContactList& res )
  : InformationElement( res )
{
}


Nepomuk::ContactList::ContactList( const Nepomuk::Resource& res )
  : InformationElement( res )
{
}


Nepomuk::ContactList::ContactList( const QString& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactList") )
{
}

Nepomuk::ContactList::ContactList( const QUrl& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactList") )
{
}

Nepomuk::ContactList::ContactList( const QString& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}

Nepomuk::ContactList::ContactList( const QUrl& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}

Nepomuk::ContactList::~ContactList()
{
}


Nepomuk::ContactList& Nepomuk::ContactList::operator=( const ContactList& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::ContactList::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactList";
}

QList<Nepomuk::ContactListDataObject> Nepomuk::ContactList::containsContacts() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    return convertResourceList<ContactListDataObject>( property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#containsContact") ).toResourceList() );
}

void Nepomuk::ContactList::setContainsContacts( const QList<Nepomuk::ContactListDataObject>& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Resource> l;
    for( QList<ContactListDataObject>::const_iterator it = value.constBegin();
         it != value.constEnd(); ++it ) {
        l.append( Resource( (*it) ) );
    }
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#containsContact"), Variant( l ) );
}

void Nepomuk::ContactList::addContainsContact( const Nepomuk::ContactListDataObject& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    Variant v = property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#containsContact") );
    v.append( Resource( value ) );
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#containsContact"), v );
}

QUrl Nepomuk::ContactList::containsContactUri()
{
    return QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#containsContact");
}

QList<Nepomuk::ContactList> Nepomuk::ContactList::allContactLists()
{
    return Nepomuk::convertResourceList<ContactList>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactList") ) );
}


