/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "contactmedium.h"

#include "role.h"
Nepomuk::ContactMedium::ContactMedium()
  : Resource( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactMedium") )
{
}


Nepomuk::ContactMedium::ContactMedium( const ContactMedium& res )
  : Resource( res )
{
}


Nepomuk::ContactMedium::ContactMedium( const Nepomuk::Resource& res )
  : Resource( res )
{
}


Nepomuk::ContactMedium::ContactMedium( const QString& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactMedium") )
{
}

Nepomuk::ContactMedium::ContactMedium( const QUrl& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactMedium") )
{
}

Nepomuk::ContactMedium::ContactMedium( const QString& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk::ContactMedium::ContactMedium( const QUrl& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk::ContactMedium::~ContactMedium()
{
}


Nepomuk::ContactMedium& Nepomuk::ContactMedium::operator=( const ContactMedium& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::ContactMedium::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactMedium";
}

QStringList Nepomuk::ContactMedium::contactMediumComments() const
{
    return ( property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactMediumComment") ).toStringList());
}

void Nepomuk::ContactMedium::setContactMediumComments( const QStringList& value )
{
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactMediumComment"), Variant( value ) );
}

void Nepomuk::ContactMedium::addContactMediumComment( const QString& value )
{
    Variant v = property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactMediumComment") );
    v.append( value );
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactMediumComment"), v );
}

QUrl Nepomuk::ContactMedium::contactMediumCommentUri()
{
    return QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactMediumComment");
}

QList<Nepomuk::Role> Nepomuk::ContactMedium::contactMediumOf() const
{
    return convertResourceList<Role>( ResourceManager::instance()->allResourcesWithProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#hasContactMedium"), *this ) );
}

QList<Nepomuk::ContactMedium> Nepomuk::ContactMedium::allContactMediums()
{
    return Nepomuk::convertResourceList<ContactMedium>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactMedium") ) );
}


