/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "datasource.h"

#include "dataobject.h"
#include "informationelement.h"
Nepomuk::DataSource::DataSource()
  : Resource( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataSource") )
{
}


Nepomuk::DataSource::DataSource( const DataSource& res )
  : Resource( res )
{
}


Nepomuk::DataSource::DataSource( const Nepomuk::Resource& res )
  : Resource( res )
{
}


Nepomuk::DataSource::DataSource( const QString& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataSource") )
{
}

Nepomuk::DataSource::DataSource( const QUrl& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataSource") )
{
}

Nepomuk::DataSource::DataSource( const QString& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk::DataSource::DataSource( const QUrl& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk::DataSource::~DataSource()
{
}


Nepomuk::DataSource& Nepomuk::DataSource::operator=( const DataSource& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::DataSource::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataSource";
}

QList<Nepomuk::DataObject> Nepomuk::DataSource::dataSourceOf() const
{
    return convertResourceList<DataObject>( ResourceManager::instance()->allResourcesWithProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/01/19/nie#dataSource"), *this ) );
}

QList<Nepomuk::InformationElement> Nepomuk::DataSource::rootElementOfOf() const
{
    return convertResourceList<InformationElement>( ResourceManager::instance()->allResourcesWithProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/01/19/nie#rootElementOf"), *this ) );
}

QList<Nepomuk::DataSource> Nepomuk::DataSource::allDataSources()
{
    return Nepomuk::convertResourceList<DataSource>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataSource") ) );
}


