/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _DOCUMENT_H_
#define _DOCUMENT_H_

namespace Nepomuk {
}

#include "informationelement.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * A generic document. A common superclass for all documents on 
 * the desktop. 
 */
    class NEPOMUK_EXPORT Document : public InformationElement
    {
    public:
        /**
         * Create a new empty and invalid Document instance
         */
        Document();
        /**
         * Default copy constructor
         */
        Document( const Document& );
        Document( const Resource& );
        /**
         * Create a new Document instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        Document( const QString& uriOrIdentifier );
        /**
         * Create a new Document instance representing the resource
         * referenced by \a uri.
         */
        Document( const QUrl& uri );
        ~Document();

        Document& operator=( const Document& );

            /**
             * Retrieve a list of all available Document resources. This list 
             * consists of all resource of type Document that are stored in 
             * the local Nepomuk meta data storage and any changes made locally. 
             * Be aware that in some cases this list can get very big. Then it 
             * might be better to use libKNep directly. 
             */
            static QList<Document> allDocuments();


        /**
         * \return The URI of the resource type that is used in Document instances.
         */
        static QString resourceTypeUri();

    protected:
       Document( const QString& uri, const QUrl& type );
       Document( const QUrl& uri, const QUrl& type );
   };
}

#endif
