/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "domesticdeliveryaddress.h"


Nepomuk::DomesticDeliveryAddress::DomesticDeliveryAddress()
  : PostalAddress( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#DomesticDeliveryAddress") )
{
}


Nepomuk::DomesticDeliveryAddress::DomesticDeliveryAddress( const DomesticDeliveryAddress& res )
  : PostalAddress( res )
{
}


Nepomuk::DomesticDeliveryAddress::DomesticDeliveryAddress( const Nepomuk::Resource& res )
  : PostalAddress( res )
{
}


Nepomuk::DomesticDeliveryAddress::DomesticDeliveryAddress( const QString& uri )
  : PostalAddress( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#DomesticDeliveryAddress") )
{
}

Nepomuk::DomesticDeliveryAddress::DomesticDeliveryAddress( const QUrl& uri )
  : PostalAddress( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#DomesticDeliveryAddress") )
{
}

Nepomuk::DomesticDeliveryAddress::DomesticDeliveryAddress( const QString& uri, const QUrl& type )
  : PostalAddress( uri, type )
{
}

Nepomuk::DomesticDeliveryAddress::DomesticDeliveryAddress( const QUrl& uri, const QUrl& type )
  : PostalAddress( uri, type )
{
}

Nepomuk::DomesticDeliveryAddress::~DomesticDeliveryAddress()
{
}


Nepomuk::DomesticDeliveryAddress& Nepomuk::DomesticDeliveryAddress::operator=( const DomesticDeliveryAddress& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::DomesticDeliveryAddress::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#DomesticDeliveryAddress";
}

QList<Nepomuk::DomesticDeliveryAddress> Nepomuk::DomesticDeliveryAddress::allDomesticDeliveryAddresss()
{
    return Nepomuk::convertResourceList<DomesticDeliveryAddress>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#DomesticDeliveryAddress") ) );
}


