/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "emailaddress.h"

#include "role.h"
Nepomuk::EmailAddress::EmailAddress()
  : ContactMedium( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#EmailAddress") )
{
}


Nepomuk::EmailAddress::EmailAddress( const EmailAddress& res )
  : ContactMedium( res )
{
}


Nepomuk::EmailAddress::EmailAddress( const Nepomuk::Resource& res )
  : ContactMedium( res )
{
}


Nepomuk::EmailAddress::EmailAddress( const QString& uri )
  : ContactMedium( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#EmailAddress") )
{
}

Nepomuk::EmailAddress::EmailAddress( const QUrl& uri )
  : ContactMedium( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#EmailAddress") )
{
}

Nepomuk::EmailAddress::EmailAddress( const QString& uri, const QUrl& type )
  : ContactMedium( uri, type )
{
}

Nepomuk::EmailAddress::EmailAddress( const QUrl& uri, const QUrl& type )
  : ContactMedium( uri, type )
{
}

Nepomuk::EmailAddress::~EmailAddress()
{
}


Nepomuk::EmailAddress& Nepomuk::EmailAddress::operator=( const EmailAddress& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::EmailAddress::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#EmailAddress";
}

QString Nepomuk::EmailAddress::emailAddress() const
{
    return ( property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#emailAddress") ).toStringList() << QString() ).first();
}

void Nepomuk::EmailAddress::setEmailAddress( const QString& value )
{
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#emailAddress"), Variant( value ) );
}

QUrl Nepomuk::EmailAddress::emailAddressUri()
{
    return QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#emailAddress");
}

QList<Nepomuk::Role> Nepomuk::EmailAddress::emailAddressOf() const
{
    return convertResourceList<Role>( ResourceManager::instance()->allResourcesWithProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#hasEmailAddress"), *this ) );
}

QList<Nepomuk::EmailAddress> Nepomuk::EmailAddress::allEmailAddresss()
{
    return Nepomuk::convertResourceList<EmailAddress>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#EmailAddress") ) );
}


