/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "filesystemimage.h"


Nepomuk::FilesystemImage::FilesystemImage()
  : Filesystem( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FilesystemImage") )
{
}


Nepomuk::FilesystemImage::FilesystemImage( const FilesystemImage& res )
  : Filesystem( res )
{
}


Nepomuk::FilesystemImage::FilesystemImage( const Nepomuk::Resource& res )
  : Filesystem( res )
{
}


Nepomuk::FilesystemImage::FilesystemImage( const QString& uri )
  : Filesystem( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FilesystemImage") )
{
}

Nepomuk::FilesystemImage::FilesystemImage( const QUrl& uri )
  : Filesystem( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FilesystemImage") )
{
}

Nepomuk::FilesystemImage::FilesystemImage( const QString& uri, const QUrl& type )
  : Filesystem( uri, type )
{
}

Nepomuk::FilesystemImage::FilesystemImage( const QUrl& uri, const QUrl& type )
  : Filesystem( uri, type )
{
}

Nepomuk::FilesystemImage::~FilesystemImage()
{
}


Nepomuk::FilesystemImage& Nepomuk::FilesystemImage::operator=( const FilesystemImage& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::FilesystemImage::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FilesystemImage";
}

QList<Nepomuk::FilesystemImage> Nepomuk::FilesystemImage::allFilesystemImages()
{
    return Nepomuk::convertResourceList<FilesystemImage>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FilesystemImage") ) );
}


