/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "filesystem.h"


Nepomuk::Filesystem::Filesystem()
  : DataContainer( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Filesystem") )
{
}


Nepomuk::Filesystem::Filesystem( const Filesystem& res )
  : DataContainer( res )
{
}


Nepomuk::Filesystem::Filesystem( const Nepomuk::Resource& res )
  : DataContainer( res )
{
}


Nepomuk::Filesystem::Filesystem( const QString& uri )
  : DataContainer( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Filesystem") )
{
}

Nepomuk::Filesystem::Filesystem( const QUrl& uri )
  : DataContainer( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Filesystem") )
{
}

Nepomuk::Filesystem::Filesystem( const QString& uri, const QUrl& type )
  : DataContainer( uri, type )
{
}

Nepomuk::Filesystem::Filesystem( const QUrl& uri, const QUrl& type )
  : DataContainer( uri, type )
{
}

Nepomuk::Filesystem::~Filesystem()
{
}


Nepomuk::Filesystem& Nepomuk::Filesystem::operator=( const Filesystem& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::Filesystem::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Filesystem";
}

QList<Nepomuk::Filesystem> Nepomuk::Filesystem::allFilesystems()
{
    return Nepomuk::convertResourceList<Filesystem>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Filesystem") ) );
}


