/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _HTMLDOCUMENT_H_
#define _HTMLDOCUMENT_H_

namespace Nepomuk {
}

#include "plaintextdocument.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * A HTML document, may contain links to other files. 
 */
    class NEPOMUK_EXPORT HtmlDocument : public PlainTextDocument
    {
    public:
        /**
         * Create a new empty and invalid HtmlDocument instance
         */
        HtmlDocument();
        /**
         * Default copy constructor
         */
        HtmlDocument( const HtmlDocument& );
        HtmlDocument( const Resource& );
        /**
         * Create a new HtmlDocument instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        HtmlDocument( const QString& uriOrIdentifier );
        /**
         * Create a new HtmlDocument instance representing the resource
         * referenced by \a uri.
         */
        HtmlDocument( const QUrl& uri );
        ~HtmlDocument();

        HtmlDocument& operator=( const HtmlDocument& );

            /**
             * Retrieve a list of all available HtmlDocument resources. This 
             * list consists of all resource of type HtmlDocument that are 
             * stored in the local Nepomuk meta data storage and any changes 
             * made locally. Be aware that in some cases this list can get very 
             * big. Then it might be better to use libKNep directly. 
             */
            static QList<HtmlDocument> allHtmlDocuments();


        /**
         * \return The URI of the resource type that is used in HtmlDocument instances.
         */
        static QString resourceTypeUri();

    protected:
       HtmlDocument( const QString& uri, const QUrl& type );
       HtmlDocument( const QUrl& uri, const QUrl& type );
   };
}

#endif
