/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _ICON_H_
#define _ICON_H_

namespace Nepomuk {
}

#include "image.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * An Icon (regardless of whether it's a raster or a vector icon. 
 * A resource representing an icon could have two types (Icon and 
 * Raster, or Icon and Vector) if required. 
 */
    class NEPOMUK_EXPORT Icon : public Image
    {
    public:
        /**
         * Create a new empty and invalid Icon instance
         */
        Icon();
        /**
         * Default copy constructor
         */
        Icon( const Icon& );
        Icon( const Resource& );
        /**
         * Create a new Icon instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        Icon( const QString& uriOrIdentifier );
        /**
         * Create a new Icon instance representing the resource
         * referenced by \a uri.
         */
        Icon( const QUrl& uri );
        ~Icon();

        Icon& operator=( const Icon& );

            /**
             * Retrieve a list of all available Icon resources. This list consists 
             * of all resource of type Icon that are stored in the local Nepomuk 
             * meta data storage and any changes made locally. Be aware that 
             * in some cases this list can get very big. Then it might be better 
             * to use libKNep directly. 
             */
            static QList<Icon> allIcons();


        /**
         * \return The URI of the resource type that is used in Icon instances.
         */
        static QString resourceTypeUri();

    protected:
       Icon( const QString& uri, const QUrl& type );
       Icon( const QUrl& uri, const QUrl& type );
   };
}

#endif
