/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _ISDNNUMBER_H_
#define _ISDNNUMBER_H_

namespace Nepomuk {
}

#include "voicephonenumber.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * An ISDN phone number. Inspired by the (TYPE=isdn) parameter 
 * of the TEL property as defined in RFC 2426 sec 3.3.1. 
 */
    class NEPOMUK_EXPORT IsdnNumber : public VoicePhoneNumber
    {
    public:
        /**
         * Create a new empty and invalid IsdnNumber instance
         */
        IsdnNumber();
        /**
         * Default copy constructor
         */
        IsdnNumber( const IsdnNumber& );
        IsdnNumber( const Resource& );
        /**
         * Create a new IsdnNumber instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        IsdnNumber( const QString& uriOrIdentifier );
        /**
         * Create a new IsdnNumber instance representing the resource
         * referenced by \a uri.
         */
        IsdnNumber( const QUrl& uri );
        ~IsdnNumber();

        IsdnNumber& operator=( const IsdnNumber& );

            /**
             * Retrieve a list of all available IsdnNumber resources. This 
             * list consists of all resource of type IsdnNumber that are stored 
             * in the local Nepomuk meta data storage and any changes made locally. 
             * Be aware that in some cases this list can get very big. Then it 
             * might be better to use libKNep directly. 
             */
            static QList<IsdnNumber> allIsdnNumbers();


        /**
         * \return The URI of the resource type that is used in IsdnNumber instances.
         */
        static QString resourceTypeUri();

    protected:
       IsdnNumber( const QString& uri, const QUrl& type );
       IsdnNumber( const QUrl& uri, const QUrl& type );
   };
}

#endif
