/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "mailbox.h"


Nepomuk::Mailbox::Mailbox()
  : InformationElement( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Mailbox") )
{
}


Nepomuk::Mailbox::Mailbox( const Mailbox& res )
  : InformationElement( res )
{
}


Nepomuk::Mailbox::Mailbox( const Nepomuk::Resource& res )
  : InformationElement( res )
{
}


Nepomuk::Mailbox::Mailbox( const QString& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Mailbox") )
{
}

Nepomuk::Mailbox::Mailbox( const QUrl& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Mailbox") )
{
}

Nepomuk::Mailbox::Mailbox( const QString& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}

Nepomuk::Mailbox::Mailbox( const QUrl& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}

Nepomuk::Mailbox::~Mailbox()
{
}


Nepomuk::Mailbox& Nepomuk::Mailbox::operator=( const Mailbox& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::Mailbox::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Mailbox";
}

QList<Nepomuk::Mailbox> Nepomuk::Mailbox::allMailboxs()
{
    return Nepomuk::convertResourceList<Mailbox>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Mailbox") ) );
}


