/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _MEDIASTREAM_H_
#define _MEDIASTREAM_H_

namespace Nepomuk {
}

#include "dataobject.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * A stream of multimedia content, usually contained within a 
 * media container such as a movie (containing both audio and video) 
 * or a DVD (possibly containing many streams of audio and video). 
 * Most common interpretations for such a DataObject include 
 * Audio and Video. 
 */
    class NEPOMUK_EXPORT MediaStream : public DataObject
    {
    public:
        /**
         * Create a new empty and invalid MediaStream instance
         */
        MediaStream();
        /**
         * Default copy constructor
         */
        MediaStream( const MediaStream& );
        MediaStream( const Resource& );
        /**
         * Create a new MediaStream instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        MediaStream( const QString& uriOrIdentifier );
        /**
         * Create a new MediaStream instance representing the resource
         * referenced by \a uri.
         */
        MediaStream( const QUrl& uri );
        ~MediaStream();

        MediaStream& operator=( const MediaStream& );

            /**
             * Retrieve a list of all available MediaStream resources. This 
             * list consists of all resource of type MediaStream that are stored 
             * in the local Nepomuk meta data storage and any changes made locally. 
             * Be aware that in some cases this list can get very big. Then it 
             * might be better to use libKNep directly. 
             */
            static QList<MediaStream> allMediaStreams();


        /**
         * \return The URI of the resource type that is used in MediaStream instances.
         */
        static QString resourceTypeUri();

    protected:
       MediaStream( const QString& uri, const QUrl& type );
       MediaStream( const QUrl& uri, const QUrl& type );
   };
}

#endif
