/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "medialist.h"

#include "mediafilelistentry.h"
Nepomuk::MediaList::MediaList()
  : InformationElement( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MediaList") )
{
}


Nepomuk::MediaList::MediaList( const MediaList& res )
  : InformationElement( res )
{
}


Nepomuk::MediaList::MediaList( const Nepomuk::Resource& res )
  : InformationElement( res )
{
}


Nepomuk::MediaList::MediaList( const QString& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MediaList") )
{
}

Nepomuk::MediaList::MediaList( const QUrl& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MediaList") )
{
}

Nepomuk::MediaList::MediaList( const QString& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}

Nepomuk::MediaList::MediaList( const QUrl& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}

Nepomuk::MediaList::~MediaList()
{
}


Nepomuk::MediaList& Nepomuk::MediaList::operator=( const MediaList& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::MediaList::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MediaList";
}

QList<Nepomuk::MediaFileListEntry> Nepomuk::MediaList::mediaFileListEntrys() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    return convertResourceList<MediaFileListEntry>( property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hasMediaFileListEntry") ).toResourceList() );
}

void Nepomuk::MediaList::setMediaFileListEntrys( const QList<Nepomuk::MediaFileListEntry>& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Resource> l;
    for( QList<MediaFileListEntry>::const_iterator it = value.constBegin();
         it != value.constEnd(); ++it ) {
        l.append( Resource( (*it) ) );
    }
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hasMediaFileListEntry"), Variant( l ) );
}

void Nepomuk::MediaList::addMediaFileListEntry( const Nepomuk::MediaFileListEntry& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    Variant v = property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hasMediaFileListEntry") );
    v.append( Resource( value ) );
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hasMediaFileListEntry"), v );
}

QUrl Nepomuk::MediaList::mediaFileListEntryUri()
{
    return QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hasMediaFileListEntry");
}

QList<Nepomuk::MediaList> Nepomuk::MediaList::allMediaLists()
{
    return Nepomuk::convertResourceList<MediaList>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#MediaList") ) );
}


