/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "modemnumber.h"


Nepomuk::ModemNumber::ModemNumber()
  : PhoneNumber( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ModemNumber") )
{
}


Nepomuk::ModemNumber::ModemNumber( const ModemNumber& res )
  : PhoneNumber( res )
{
}


Nepomuk::ModemNumber::ModemNumber( const Nepomuk::Resource& res )
  : PhoneNumber( res )
{
}


Nepomuk::ModemNumber::ModemNumber( const QString& uri )
  : PhoneNumber( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ModemNumber") )
{
}

Nepomuk::ModemNumber::ModemNumber( const QUrl& uri )
  : PhoneNumber( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ModemNumber") )
{
}

Nepomuk::ModemNumber::ModemNumber( const QString& uri, const QUrl& type )
  : PhoneNumber( uri, type )
{
}

Nepomuk::ModemNumber::ModemNumber( const QUrl& uri, const QUrl& type )
  : PhoneNumber( uri, type )
{
}

Nepomuk::ModemNumber::~ModemNumber()
{
}


Nepomuk::ModemNumber& Nepomuk::ModemNumber::operator=( const ModemNumber& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::ModemNumber::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ModemNumber";
}

QList<Nepomuk::ModemNumber> Nepomuk::ModemNumber::allModemNumbers()
{
    return Nepomuk::convertResourceList<ModemNumber>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ModemNumber") ) );
}


