/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "pagernumber.h"


Nepomuk::PagerNumber::PagerNumber()
  : MessagingNumber( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PagerNumber") )
{
}


Nepomuk::PagerNumber::PagerNumber( const PagerNumber& res )
  : MessagingNumber( res )
{
}


Nepomuk::PagerNumber::PagerNumber( const Nepomuk::Resource& res )
  : MessagingNumber( res )
{
}


Nepomuk::PagerNumber::PagerNumber( const QString& uri )
  : MessagingNumber( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PagerNumber") )
{
}

Nepomuk::PagerNumber::PagerNumber( const QUrl& uri )
  : MessagingNumber( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PagerNumber") )
{
}

Nepomuk::PagerNumber::PagerNumber( const QString& uri, const QUrl& type )
  : MessagingNumber( uri, type )
{
}

Nepomuk::PagerNumber::PagerNumber( const QUrl& uri, const QUrl& type )
  : MessagingNumber( uri, type )
{
}

Nepomuk::PagerNumber::~PagerNumber()
{
}


Nepomuk::PagerNumber& Nepomuk::PagerNumber::operator=( const PagerNumber& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::PagerNumber::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PagerNumber";
}

QList<Nepomuk::PagerNumber> Nepomuk::PagerNumber::allPagerNumbers()
{
    return Nepomuk::convertResourceList<PagerNumber>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PagerNumber") ) );
}


