/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "parceldeliveryaddress.h"


Nepomuk::ParcelDeliveryAddress::ParcelDeliveryAddress()
  : PostalAddress( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress") )
{
}


Nepomuk::ParcelDeliveryAddress::ParcelDeliveryAddress( const ParcelDeliveryAddress& res )
  : PostalAddress( res )
{
}


Nepomuk::ParcelDeliveryAddress::ParcelDeliveryAddress( const Nepomuk::Resource& res )
  : PostalAddress( res )
{
}


Nepomuk::ParcelDeliveryAddress::ParcelDeliveryAddress( const QString& uri )
  : PostalAddress( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress") )
{
}

Nepomuk::ParcelDeliveryAddress::ParcelDeliveryAddress( const QUrl& uri )
  : PostalAddress( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress") )
{
}

Nepomuk::ParcelDeliveryAddress::ParcelDeliveryAddress( const QString& uri, const QUrl& type )
  : PostalAddress( uri, type )
{
}

Nepomuk::ParcelDeliveryAddress::ParcelDeliveryAddress( const QUrl& uri, const QUrl& type )
  : PostalAddress( uri, type )
{
}

Nepomuk::ParcelDeliveryAddress::~ParcelDeliveryAddress()
{
}


Nepomuk::ParcelDeliveryAddress& Nepomuk::ParcelDeliveryAddress::operator=( const ParcelDeliveryAddress& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::ParcelDeliveryAddress::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress";
}

QList<Nepomuk::ParcelDeliveryAddress> Nepomuk::ParcelDeliveryAddress::allParcelDeliveryAddresss()
{
    return Nepomuk::convertResourceList<ParcelDeliveryAddress>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress") ) );
}


