/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "pcsnumber.h"


Nepomuk::PcsNumber::PcsNumber()
  : VoicePhoneNumber( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PcsNumber") )
{
}


Nepomuk::PcsNumber::PcsNumber( const PcsNumber& res )
  : VoicePhoneNumber( res )
{
}


Nepomuk::PcsNumber::PcsNumber( const Nepomuk::Resource& res )
  : VoicePhoneNumber( res )
{
}


Nepomuk::PcsNumber::PcsNumber( const QString& uri )
  : VoicePhoneNumber( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PcsNumber") )
{
}

Nepomuk::PcsNumber::PcsNumber( const QUrl& uri )
  : VoicePhoneNumber( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PcsNumber") )
{
}

Nepomuk::PcsNumber::PcsNumber( const QString& uri, const QUrl& type )
  : VoicePhoneNumber( uri, type )
{
}

Nepomuk::PcsNumber::PcsNumber( const QUrl& uri, const QUrl& type )
  : VoicePhoneNumber( uri, type )
{
}

Nepomuk::PcsNumber::~PcsNumber()
{
}


Nepomuk::PcsNumber& Nepomuk::PcsNumber::operator=( const PcsNumber& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::PcsNumber::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PcsNumber";
}

QList<Nepomuk::PcsNumber> Nepomuk::PcsNumber::allPcsNumbers()
{
    return Nepomuk::convertResourceList<PcsNumber>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PcsNumber") ) );
}


