/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "phonenumber.h"

#include "role.h"
Nepomuk::PhoneNumber::PhoneNumber()
  : ContactMedium( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PhoneNumber") )
{
}


Nepomuk::PhoneNumber::PhoneNumber( const PhoneNumber& res )
  : ContactMedium( res )
{
}


Nepomuk::PhoneNumber::PhoneNumber( const Nepomuk::Resource& res )
  : ContactMedium( res )
{
}


Nepomuk::PhoneNumber::PhoneNumber( const QString& uri )
  : ContactMedium( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PhoneNumber") )
{
}

Nepomuk::PhoneNumber::PhoneNumber( const QUrl& uri )
  : ContactMedium( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PhoneNumber") )
{
}

Nepomuk::PhoneNumber::PhoneNumber( const QString& uri, const QUrl& type )
  : ContactMedium( uri, type )
{
}

Nepomuk::PhoneNumber::PhoneNumber( const QUrl& uri, const QUrl& type )
  : ContactMedium( uri, type )
{
}

Nepomuk::PhoneNumber::~PhoneNumber()
{
}


Nepomuk::PhoneNumber& Nepomuk::PhoneNumber::operator=( const PhoneNumber& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::PhoneNumber::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PhoneNumber";
}

QStringList Nepomuk::PhoneNumber::phoneNumbers() const
{
    return ( property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#phoneNumber") ).toStringList());
}

void Nepomuk::PhoneNumber::setPhoneNumbers( const QStringList& value )
{
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#phoneNumber"), Variant( value ) );
}

void Nepomuk::PhoneNumber::addPhoneNumber( const QString& value )
{
    Variant v = property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#phoneNumber") );
    v.append( value );
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#phoneNumber"), v );
}

QUrl Nepomuk::PhoneNumber::phoneNumberUri()
{
    return QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#phoneNumber");
}

QList<Nepomuk::Role> Nepomuk::PhoneNumber::phoneNumberOf() const
{
    return convertResourceList<Role>( ResourceManager::instance()->allResourcesWithProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#hasPhoneNumber"), *this ) );
}

QList<Nepomuk::PhoneNumber> Nepomuk::PhoneNumber::allPhoneNumbers()
{
    return Nepomuk::convertResourceList<PhoneNumber>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#PhoneNumber") ) );
}


