/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "plaintextdocument.h"


Nepomuk::PlainTextDocument::PlainTextDocument()
  : TextDocument( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument") )
{
}


Nepomuk::PlainTextDocument::PlainTextDocument( const PlainTextDocument& res )
  : TextDocument( res )
{
}


Nepomuk::PlainTextDocument::PlainTextDocument( const Nepomuk::Resource& res )
  : TextDocument( res )
{
}


Nepomuk::PlainTextDocument::PlainTextDocument( const QString& uri )
  : TextDocument( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument") )
{
}

Nepomuk::PlainTextDocument::PlainTextDocument( const QUrl& uri )
  : TextDocument( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument") )
{
}

Nepomuk::PlainTextDocument::PlainTextDocument( const QString& uri, const QUrl& type )
  : TextDocument( uri, type )
{
}

Nepomuk::PlainTextDocument::PlainTextDocument( const QUrl& uri, const QUrl& type )
  : TextDocument( uri, type )
{
}

Nepomuk::PlainTextDocument::~PlainTextDocument()
{
}


Nepomuk::PlainTextDocument& Nepomuk::PlainTextDocument::operator=( const PlainTextDocument& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::PlainTextDocument::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument";
}

QList<Nepomuk::PlainTextDocument> Nepomuk::PlainTextDocument::allPlainTextDocuments()
{
    return Nepomuk::convertResourceList<PlainTextDocument>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument") ) );
}


