/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _PLAINTEXTDOCUMENT_H_
#define _PLAINTEXTDOCUMENT_H_

namespace Nepomuk {
}

#include "textdocument.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * A file containing plain text (ASCII, Unicode or other encodings). 
 * Examples may include TXT, HTML, XML, program source code etc. 
 */
    class NEPOMUK_EXPORT PlainTextDocument : public TextDocument
    {
    public:
        /**
         * Create a new empty and invalid PlainTextDocument instance
         */
        PlainTextDocument();
        /**
         * Default copy constructor
         */
        PlainTextDocument( const PlainTextDocument& );
        PlainTextDocument( const Resource& );
        /**
         * Create a new PlainTextDocument instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        PlainTextDocument( const QString& uriOrIdentifier );
        /**
         * Create a new PlainTextDocument instance representing the resource
         * referenced by \a uri.
         */
        PlainTextDocument( const QUrl& uri );
        ~PlainTextDocument();

        PlainTextDocument& operator=( const PlainTextDocument& );

            /**
             * Retrieve a list of all available PlainTextDocument resources. 
             * This list consists of all resource of type PlainTextDocument 
             * that are stored in the local Nepomuk meta data storage and any 
             * changes made locally. Be aware that in some cases this list can 
             * get very big. Then it might be better to use libKNep directly. 
             */
            static QList<PlainTextDocument> allPlainTextDocuments();


        /**
         * \return The URI of the resource type that is used in PlainTextDocument instances.
         */
        static QString resourceTypeUri();

    protected:
       PlainTextDocument( const QString& uri, const QUrl& type );
       PlainTextDocument( const QUrl& uri, const QUrl& type );
   };
}

#endif
