/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "remotedataobject.h"


Nepomuk::RemoteDataObject::RemoteDataObject()
  : FileDataObject( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#RemoteDataObject") )
{
}


Nepomuk::RemoteDataObject::RemoteDataObject( const RemoteDataObject& res )
  : FileDataObject( res )
{
}


Nepomuk::RemoteDataObject::RemoteDataObject( const Nepomuk::Resource& res )
  : FileDataObject( res )
{
}


Nepomuk::RemoteDataObject::RemoteDataObject( const QString& uri )
  : FileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#RemoteDataObject") )
{
}

Nepomuk::RemoteDataObject::RemoteDataObject( const QUrl& uri )
  : FileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#RemoteDataObject") )
{
}

Nepomuk::RemoteDataObject::RemoteDataObject( const QString& uri, const QUrl& type )
  : FileDataObject( uri, type )
{
}

Nepomuk::RemoteDataObject::RemoteDataObject( const QUrl& uri, const QUrl& type )
  : FileDataObject( uri, type )
{
}

Nepomuk::RemoteDataObject::~RemoteDataObject()
{
}


Nepomuk::RemoteDataObject& Nepomuk::RemoteDataObject::operator=( const RemoteDataObject& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::RemoteDataObject::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#RemoteDataObject";
}

QList<Nepomuk::RemoteDataObject> Nepomuk::RemoteDataObject::allRemoteDataObjects()
{
    return Nepomuk::convertResourceList<RemoteDataObject>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#RemoteDataObject") ) );
}


