/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _REMOTEPORTADDRESS_H_
#define _REMOTEPORTADDRESS_H_

namespace Nepomuk {
}

#include "dataobject.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * An address specifying a remote host and port. Such an address 
 * can be interpreted in many ways (examples of such interpretations 
 * include mailboxes, websites, remote calendars or filesystems), 
 * depending on an interpretation, various kinds of data may be 
 * extracted from such an address. 
 */
    class NEPOMUK_EXPORT RemotePortAddress : public DataObject
    {
    public:
        /**
         * Create a new empty and invalid RemotePortAddress instance
         */
        RemotePortAddress();
        /**
         * Default copy constructor
         */
        RemotePortAddress( const RemotePortAddress& );
        RemotePortAddress( const Resource& );
        /**
         * Create a new RemotePortAddress instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        RemotePortAddress( const QString& uriOrIdentifier );
        /**
         * Create a new RemotePortAddress instance representing the resource
         * referenced by \a uri.
         */
        RemotePortAddress( const QUrl& uri );
        ~RemotePortAddress();

        RemotePortAddress& operator=( const RemotePortAddress& );

            /**
             * Retrieve a list of all available RemotePortAddress resources. 
             * This list consists of all resource of type RemotePortAddress 
             * that are stored in the local Nepomuk meta data storage and any 
             * changes made locally. Be aware that in some cases this list can 
             * get very big. Then it might be better to use libKNep directly. 
             */
            static QList<RemotePortAddress> allRemotePortAddresss();


        /**
         * \return The URI of the resource type that is used in RemotePortAddress instances.
         */
        static QString resourceTypeUri();

    protected:
       RemotePortAddress( const QString& uri, const QUrl& type );
       RemotePortAddress( const QUrl& uri, const QUrl& type );
   };
}

#endif
