/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _SOFTWAREITEM_H_
#define _SOFTWAREITEM_H_

namespace Nepomuk {
}

#include "dataobject.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * A DataObject representing a piece of software. Examples of 
 * interpretations of a SoftwareItem include an Application 
 * and an OperatingSystem. 
 */
    class NEPOMUK_EXPORT SoftwareItem : public DataObject
    {
    public:
        /**
         * Create a new empty and invalid SoftwareItem instance
         */
        SoftwareItem();
        /**
         * Default copy constructor
         */
        SoftwareItem( const SoftwareItem& );
        SoftwareItem( const Resource& );
        /**
         * Create a new SoftwareItem instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        SoftwareItem( const QString& uriOrIdentifier );
        /**
         * Create a new SoftwareItem instance representing the resource
         * referenced by \a uri.
         */
        SoftwareItem( const QUrl& uri );
        ~SoftwareItem();

        SoftwareItem& operator=( const SoftwareItem& );

            /**
             * Retrieve a list of all available SoftwareItem resources. This 
             * list consists of all resource of type SoftwareItem that are 
             * stored in the local Nepomuk meta data storage and any changes 
             * made locally. Be aware that in some cases this list can get very 
             * big. Then it might be better to use libKNep directly. 
             */
            static QList<SoftwareItem> allSoftwareItems();


        /**
         * \return The URI of the resource type that is used in SoftwareItem instances.
         */
        static QString resourceTypeUri();

    protected:
       SoftwareItem( const QString& uri, const QUrl& type );
       SoftwareItem( const QUrl& uri, const QUrl& type );
   };
}

#endif
