/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "spreadsheet.h"


Nepomuk::Spreadsheet::Spreadsheet()
  : Document( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet") )
{
}


Nepomuk::Spreadsheet::Spreadsheet( const Spreadsheet& res )
  : Document( res )
{
}


Nepomuk::Spreadsheet::Spreadsheet( const Nepomuk::Resource& res )
  : Document( res )
{
}


Nepomuk::Spreadsheet::Spreadsheet( const QString& uri )
  : Document( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet") )
{
}

Nepomuk::Spreadsheet::Spreadsheet( const QUrl& uri )
  : Document( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet") )
{
}

Nepomuk::Spreadsheet::Spreadsheet( const QString& uri, const QUrl& type )
  : Document( uri, type )
{
}

Nepomuk::Spreadsheet::Spreadsheet( const QUrl& uri, const QUrl& type )
  : Document( uri, type )
{
}

Nepomuk::Spreadsheet::~Spreadsheet()
{
}


Nepomuk::Spreadsheet& Nepomuk::Spreadsheet::operator=( const Spreadsheet& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::Spreadsheet::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet";
}

QList<Nepomuk::Spreadsheet> Nepomuk::Spreadsheet::allSpreadsheets()
{
    return Nepomuk::convertResourceList<Spreadsheet>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet") ) );
}


