/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _TRASH_H_
#define _TRASH_H_

namespace Nepomuk {
}

#include "datacontainer.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {

/**
 * Represents a container for deleted files, a feature common 
 * in modern operating systems. 
 */
    class NEPOMUK_EXPORT Trash : public DataContainer
    {
    public:
        /**
         * Create a new empty and invalid Trash instance
         */
        Trash();
        /**
         * Default copy constructor
         */
        Trash( const Trash& );
        Trash( const Resource& );
        /**
         * Create a new Trash instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        Trash( const QString& uriOrIdentifier );
        /**
         * Create a new Trash instance representing the resource
         * referenced by \a uri.
         */
        Trash( const QUrl& uri );
        ~Trash();

        Trash& operator=( const Trash& );

            /**
             * Retrieve a list of all available Trash resources. This list 
             * consists of all resource of type Trash that are stored in the 
             * local Nepomuk meta data storage and any changes made locally. 
             * Be aware that in some cases this list can get very big. Then it 
             * might be better to use libKNep directly. 
             */
            static QList<Trash> allTrashs();


        /**
         * \return The URI of the resource type that is used in Trash instances.
         */
        static QString resourceTypeUri();

    protected:
       Trash( const QString& uri, const QUrl& type );
       Trash( const QUrl& uri, const QUrl& type );
   };
}

#endif
