/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "vectorimage.h"


Nepomuk::VectorImage::VectorImage()
  : Image( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#VectorImage") )
{
}


Nepomuk::VectorImage::VectorImage( const VectorImage& res )
  : Image( res )
{
}


Nepomuk::VectorImage::VectorImage( const Nepomuk::Resource& res )
  : Image( res )
{
}


Nepomuk::VectorImage::VectorImage( const QString& uri )
  : Image( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#VectorImage") )
{
}

Nepomuk::VectorImage::VectorImage( const QUrl& uri )
  : Image( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#VectorImage") )
{
}

Nepomuk::VectorImage::VectorImage( const QString& uri, const QUrl& type )
  : Image( uri, type )
{
}

Nepomuk::VectorImage::VectorImage( const QUrl& uri, const QUrl& type )
  : Image( uri, type )
{
}

Nepomuk::VectorImage::~VectorImage()
{
}


Nepomuk::VectorImage& Nepomuk::VectorImage::operator=( const VectorImage& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::VectorImage::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#VectorImage";
}

QList<Nepomuk::VectorImage> Nepomuk::VectorImage::allVectorImages()
{
    return Nepomuk::convertResourceList<VectorImage>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#VectorImage") ) );
}


