/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _VECTORIMAGE_H_
#define _VECTORIMAGE_H_

namespace Nepomuk {
}

#include "image.h"
#include <nepomuk/nepomuk_export.h>

namespace Nepomuk {


    class NEPOMUK_EXPORT VectorImage : public Image
    {
    public:
        /**
         * Create a new empty and invalid VectorImage instance
         */
        VectorImage();
        /**
         * Default copy constructor
         */
        VectorImage( const VectorImage& );
        VectorImage( const Resource& );
        /**
         * Create a new VectorImage instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        VectorImage( const QString& uriOrIdentifier );
        /**
         * Create a new VectorImage instance representing the resource
         * referenced by \a uri.
         */
        VectorImage( const QUrl& uri );
        ~VectorImage();

        VectorImage& operator=( const VectorImage& );

            /**
             * Retrieve a list of all available VectorImage resources. This 
             * list consists of all resource of type VectorImage that are stored 
             * in the local Nepomuk meta data storage and any changes made locally. 
             * Be aware that in some cases this list can get very big. Then it 
             * might be better to use libKNep directly. 
             */
            static QList<VectorImage> allVectorImages();


        /**
         * \return The URI of the resource type that is used in VectorImage instances.
         */
        static QString resourceTypeUri();

    protected:
       VectorImage( const QString& uri, const QUrl& type );
       VectorImage( const QUrl& uri, const QUrl& type );
   };
}

#endif
