/*
 *
 * $Id: $
 *
 * This file is part of the Nepomuk KDE project.
 * Copyright (C) 2007 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk/tools.h>
#include <nepomuk/variant.h>
#include <nepomuk/resourcemanager.h>
#include "video.h"


Nepomuk::Video::Video()
  : Visual( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Video") )
{
}


Nepomuk::Video::Video( const Video& res )
  : Visual( res )
{
}


Nepomuk::Video::Video( const Nepomuk::Resource& res )
  : Visual( res )
{
}


Nepomuk::Video::Video( const QString& uri )
  : Visual( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Video") )
{
}

Nepomuk::Video::Video( const QUrl& uri )
  : Visual( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Video") )
{
}

Nepomuk::Video::Video( const QString& uri, const QUrl& type )
  : Visual( uri, type )
{
}

Nepomuk::Video::Video( const QUrl& uri, const QUrl& type )
  : Visual( uri, type )
{
}

Nepomuk::Video::~Video()
{
}


Nepomuk::Video& Nepomuk::Video::operator=( const Video& res )
{
    Resource::operator=( res );
    return *this;
}


QString Nepomuk::Video::resourceTypeUri()
{
    return "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Video";
}

QList<double> Nepomuk::Video::frameRates() const
{
    return ( property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameRate") ).toDoubleList());
}

void Nepomuk::Video::setFrameRates( const QList<double>& value )
{
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameRate"), Variant( value ) );
}

void Nepomuk::Video::addFrameRate( const double& value )
{
    Variant v = property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameRate") );
    v.append( value );
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameRate"), v );
}

QUrl Nepomuk::Video::frameRateUri()
{
    return QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameRate");
}

QList<qint64> Nepomuk::Video::frameCounts() const
{
    return ( property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameCount") ).toInt64List());
}

void Nepomuk::Video::setFrameCounts( const QList<qint64>& value )
{
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameCount"), Variant( value ) );
}

void Nepomuk::Video::addFrameCount( const qint64& value )
{
    Variant v = property( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameCount") );
    v.append( value );
    setProperty( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameCount"), v );
}

QUrl Nepomuk::Video::frameCountUri()
{
    return QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#frameCount");
}

QList<Nepomuk::Video> Nepomuk::Video::allVideos()
{
    return Nepomuk::convertResourceList<Video>( ResourceManager::instance()->allResourcesOfType( QUrl("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Video") ) );
}


