/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -m -a searchprovideradaptor -i searchproviderbase.h -l Akonadi::SearchProvider /k/kde4/src/kdepim/akonadi/searchproviders/org.kde.Akonadi.SearchProvider.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "searchprovideradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SearchProviderAdaptor
 */

SearchProviderAdaptor::SearchProviderAdaptor(Akonadi::SearchProvider *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SearchProviderAdaptor::~SearchProviderAdaptor()
{
    // destructor
}

QStringList SearchProviderAdaptor::fetchResponse(const QStringList &uids, const QString &field, const QDBusMessage &msg)
{
    // handle method call org.kde.Akonadi.SearchProvider.fetchResponse
    return parent()->fetchResponse(uids, field, msg);
}

void SearchProviderAdaptor::quit()
{
    // handle method call org.kde.Akonadi.SearchProvider.quit
    parent()->quit();
}

int SearchProviderAdaptor::search(const QString &targetCollection, const QString &searchQuery)
{
    // handle method call org.kde.Akonadi.SearchProvider.search
    return parent()->search(targetCollection, searchQuery);
}


#include "searchprovideradaptor.moc"
