/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a searchprovideradaptor -c SearchProviderAdaptor -i searchproviderbase.h -l SearchProviderBase -m org.kde.Akonadi.SearchProvider.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "searchprovideradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SearchProviderAdaptor
 */

SearchProviderAdaptor::SearchProviderAdaptor(Akonadi::SearchProviderBase *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SearchProviderAdaptor::~SearchProviderAdaptor()
{
    // destructor
}

bool SearchProviderAdaptor::addSearch(const QString &targetCollection, const QString &searchQuery, const QDBusMessage &msg)
{
    // handle method call org.kde.Akonadi.SearchProvider.addSearch
    return parent()->addSearch(targetCollection, searchQuery, msg);
}

QStringList SearchProviderAdaptor::fetchResponse(const QStringList &uids, const QString &field, const QDBusMessage &msg)
{
    // handle method call org.kde.Akonadi.SearchProvider.fetchResponse
    return parent()->fetchResponse(uids, field, msg);
}

void SearchProviderAdaptor::quit()
{
    // handle method call org.kde.Akonadi.SearchProvider.quit
    parent()->quit();
}

bool SearchProviderAdaptor::removeSearch(const QString &collection)
{
    // handle method call org.kde.Akonadi.SearchProvider.removeSearch
    return parent()->removeSearch(collection);
}


#include "searchprovideradaptor.moc"
