/*
 * This file has been generated by the onto2vocabularyclass tool
 * copyright (C) 2007-2008 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "ncal.h"

class NcalPrivate
{
public:
    NcalPrivate()
        : ncal_namespace( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#", QUrl::StrictMode ) ),
          ncal_AccessClassification( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#AccessClassification", QUrl::StrictMode ) ),
          ncal_Alarm( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Alarm", QUrl::StrictMode ) ),
          ncal_AlarmAction( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#AlarmAction", QUrl::StrictMode ) ),
          ncal_Attachment( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Attachment", QUrl::StrictMode ) ),
          ncal_AttachmentEncoding( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#AttachmentEncoding", QUrl::StrictMode ) ),
          ncal_Attendee( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Attendee", QUrl::StrictMode ) ),
          ncal_AttendeeOrOrganizer( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#AttendeeOrOrganizer", QUrl::StrictMode ) ),
          ncal_AttendeeRole( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#AttendeeRole", QUrl::StrictMode ) ),
          ncal_BydayRulePart( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#BydayRulePart", QUrl::StrictMode ) ),
          ncal_Calendar( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Calendar", QUrl::StrictMode ) ),
          ncal_CalendarDataObject( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#CalendarDataObject", QUrl::StrictMode ) ),
          ncal_CalendarScale( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#CalendarScale", QUrl::StrictMode ) ),
          ncal_CalendarUserType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#CalendarUserType", QUrl::StrictMode ) ),
          ncal_Event( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Event", QUrl::StrictMode ) ),
          ncal_EventStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#EventStatus", QUrl::StrictMode ) ),
          ncal_Freebusy( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Freebusy", QUrl::StrictMode ) ),
          ncal_FreebusyPeriod( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#FreebusyPeriod", QUrl::StrictMode ) ),
          ncal_FreebusyType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#FreebusyType", QUrl::StrictMode ) ),
          ncal_Journal( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Journal", QUrl::StrictMode ) ),
          ncal_JournalStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#JournalStatus", QUrl::StrictMode ) ),
          ncal_NcalDateTime( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#NcalDateTime", QUrl::StrictMode ) ),
          ncal_NcalPeriod( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#NcalPeriod", QUrl::StrictMode ) ),
          ncal_NcalTimeEntity( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#NcalTimeEntity", QUrl::StrictMode ) ),
          ncal_Organizer( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Organizer", QUrl::StrictMode ) ),
          ncal_ParticipationStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#ParticipationStatus", QUrl::StrictMode ) ),
          ncal_RecurrenceFrequency( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#RecurrenceFrequency", QUrl::StrictMode ) ),
          ncal_RecurrenceIdentifier( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#RecurrenceIdentifier", QUrl::StrictMode ) ),
          ncal_RecurrenceIdentifierRange( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#RecurrenceIdentifierRange", QUrl::StrictMode ) ),
          ncal_RecurrenceRule( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#RecurrenceRule", QUrl::StrictMode ) ),
          ncal_RequestStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#RequestStatus", QUrl::StrictMode ) ),
          ncal_TimeTransparency( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#TimeTransparency", QUrl::StrictMode ) ),
          ncal_Timezone( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Timezone", QUrl::StrictMode ) ),
          ncal_TimezoneObservance( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#TimezoneObservance", QUrl::StrictMode ) ),
          ncal_Todo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Todo", QUrl::StrictMode ) ),
          ncal_TodoStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#TodoStatus", QUrl::StrictMode ) ),
          ncal_Trigger( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Trigger", QUrl::StrictMode ) ),
          ncal_TriggerRelation( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#TriggerRelation", QUrl::StrictMode ) ),
          ncal_UnionOfAlarmEventFreebusyJournalTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfAlarmEventFreebusyJournalTodo", QUrl::StrictMode ) ),
          ncal_UnionOfAlarmEventFreebusyTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfAlarmEventFreebusyTodo", QUrl::StrictMode ) ),
          ncal_UnionOfAlarmEventJournalTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfAlarmEventJournalTodo", QUrl::StrictMode ) ),
          ncal_UnionOfAlarmEventTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfAlarmEventTodo", QUrl::StrictMode ) ),
          ncal_UnionOfEventFreebusy( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfEventFreebusy", QUrl::StrictMode ) ),
          ncal_UnionOfEventFreebusyJournalTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfEventFreebusyJournalTodo", QUrl::StrictMode ) ),
          ncal_UnionOfEventJournalTimezoneTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfEventJournalTimezoneTodo", QUrl::StrictMode ) ),
          ncal_UnionOfEventJournalTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfEventJournalTodo", QUrl::StrictMode ) ),
          ncal_UnionOfEventTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfEventTodo", QUrl::StrictMode ) ),
          ncal_UnionOfTimezoneObservanceEventFreebusyJournalTimezoneTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfTimezoneObservanceEventFreebusyJournalTimezoneTodo", QUrl::StrictMode ) ),
          ncal_UnionOfTimezoneObservanceEventFreebusyTimezoneTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfTimezoneObservanceEventFreebusyTimezoneTodo", QUrl::StrictMode ) ),
          ncal_UnionOfTimezoneObservanceEventJournalTimezoneTodo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionOfTimezoneObservanceEventJournalTimezoneTodo", QUrl::StrictMode ) ),
          ncal_UnionParentClass( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#UnionParentClass", QUrl::StrictMode ) ),
          ncal_Weekday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#Weekday", QUrl::StrictMode ) ),
          ncal__8bitEncoding( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#_8bitEncoding", QUrl::StrictMode ) ),
          ncal_acceptedParticipationStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#acceptedParticipationStatus", QUrl::StrictMode ) ),
          ncal_action( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#action", QUrl::StrictMode ) ),
          ncal_attach( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#attach", QUrl::StrictMode ) ),
          ncal_attachmentContent( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#attachmentContent", QUrl::StrictMode ) ),
          ncal_attachmentUri( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#attachmentUri", QUrl::StrictMode ) ),
          ncal_attendee( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#attendee", QUrl::StrictMode ) ),
          ncal_audioAction( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#audioAction", QUrl::StrictMode ) ),
          ncal_base64Encoding( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#base64Encoding", QUrl::StrictMode ) ),
          ncal_busyFreebusyType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#busyFreebusyType", QUrl::StrictMode ) ),
          ncal_busyTentativeFreebusyType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#busyTentativeFreebusyType", QUrl::StrictMode ) ),
          ncal_busyUnavailableFreebusyType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#busyUnavailableFreebusyType", QUrl::StrictMode ) ),
          ncal_byday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#byday", QUrl::StrictMode ) ),
          ncal_bydayModifier( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#bydayModifier", QUrl::StrictMode ) ),
          ncal_bydayWeekday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#bydayWeekday", QUrl::StrictMode ) ),
          ncal_byhour( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#byhour", QUrl::StrictMode ) ),
          ncal_byminute( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#byminute", QUrl::StrictMode ) ),
          ncal_bymonth( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#bymonth", QUrl::StrictMode ) ),
          ncal_bymonthday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#bymonthday", QUrl::StrictMode ) ),
          ncal_bysecond( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#bysecond", QUrl::StrictMode ) ),
          ncal_bysetpos( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#bysetpos", QUrl::StrictMode ) ),
          ncal_byweekno( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#byweekno", QUrl::StrictMode ) ),
          ncal_byyearday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#byyearday", QUrl::StrictMode ) ),
          ncal_calscale( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#calscale", QUrl::StrictMode ) ),
          ncal_cancelledEventStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#cancelledEventStatus", QUrl::StrictMode ) ),
          ncal_cancelledJournalStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#cancelledJournalStatus", QUrl::StrictMode ) ),
          ncal_cancelledTodoStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#cancelledTodoStatus", QUrl::StrictMode ) ),
          ncal_categories( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#categories", QUrl::StrictMode ) ),
          ncal_chairRole( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#chairRole", QUrl::StrictMode ) ),
          ncal_class( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#class", QUrl::StrictMode ) ),
          ncal_comment( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#comment", QUrl::StrictMode ) ),
          ncal_commentAltRep( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#commentAltRep", QUrl::StrictMode ) ),
          ncal_completed( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#completed", QUrl::StrictMode ) ),
          ncal_completedParticipationStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#completedParticipationStatus", QUrl::StrictMode ) ),
          ncal_completedStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#completedStatus", QUrl::StrictMode ) ),
          ncal_component( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#component", QUrl::StrictMode ) ),
          ncal_confidentialClassification( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#confidentialClassification", QUrl::StrictMode ) ),
          ncal_confirmedStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#confirmedStatus", QUrl::StrictMode ) ),
          ncal_contact( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#contact", QUrl::StrictMode ) ),
          ncal_contactAltRep( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#contactAltRep", QUrl::StrictMode ) ),
          ncal_count( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#count", QUrl::StrictMode ) ),
          ncal_created( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#created", QUrl::StrictMode ) ),
          ncal_cutype( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#cutype", QUrl::StrictMode ) ),
          ncal_daily( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#daily", QUrl::StrictMode ) ),
          ncal_date( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#date", QUrl::StrictMode ) ),
          ncal_dateTime( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#dateTime", QUrl::StrictMode ) ),
          ncal_daylight( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#daylight", QUrl::StrictMode ) ),
          ncal_declinedParticipationStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#declinedParticipationStatus", QUrl::StrictMode ) ),
          ncal_delegatedFrom( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#delegatedFrom", QUrl::StrictMode ) ),
          ncal_delegatedParticipationStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#delegatedParticipationStatus", QUrl::StrictMode ) ),
          ncal_delegatedTo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#delegatedTo", QUrl::StrictMode ) ),
          ncal_description( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#description", QUrl::StrictMode ) ),
          ncal_descriptionAltRep( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#descriptionAltRep", QUrl::StrictMode ) ),
          ncal_dir( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#dir", QUrl::StrictMode ) ),
          ncal_displayAction( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#displayAction", QUrl::StrictMode ) ),
          ncal_draftStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#draftStatus", QUrl::StrictMode ) ),
          ncal_dtend( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#dtend", QUrl::StrictMode ) ),
          ncal_dtstamp( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#dtstamp", QUrl::StrictMode ) ),
          ncal_dtstart( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#dtstart", QUrl::StrictMode ) ),
          ncal_due( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#due", QUrl::StrictMode ) ),
          ncal_duration( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#duration", QUrl::StrictMode ) ),
          ncal_emailAction( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#emailAction", QUrl::StrictMode ) ),
          ncal_encoding( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#encoding", QUrl::StrictMode ) ),
          ncal_endTriggerRelation( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#endTriggerRelation", QUrl::StrictMode ) ),
          ncal_eventStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#eventStatus", QUrl::StrictMode ) ),
          ncal_exdate( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#exdate", QUrl::StrictMode ) ),
          ncal_exrule( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#exrule", QUrl::StrictMode ) ),
          ncal_fbtype( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#fbtype", QUrl::StrictMode ) ),
          ncal_finalStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#finalStatus", QUrl::StrictMode ) ),
          ncal_fmttype( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#fmttype", QUrl::StrictMode ) ),
          ncal_freeFreebusyType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#freeFreebusyType", QUrl::StrictMode ) ),
          ncal_freebusy( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#freebusy", QUrl::StrictMode ) ),
          ncal_freq( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#freq", QUrl::StrictMode ) ),
          ncal_friday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#friday", QUrl::StrictMode ) ),
          ncal_geo( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#geo", QUrl::StrictMode ) ),
          ncal_gregorianCalendarScale( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#gregorianCalendarScale", QUrl::StrictMode ) ),
          ncal_groupUserType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#groupUserType", QUrl::StrictMode ) ),
          ncal_hasAlarm( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#hasAlarm", QUrl::StrictMode ) ),
          ncal_hourly( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#hourly", QUrl::StrictMode ) ),
          ncal_inProcessParticipationStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#inProcessParticipationStatus", QUrl::StrictMode ) ),
          ncal_inProcessStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#inProcessStatus", QUrl::StrictMode ) ),
          ncal_individualUserType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#individualUserType", QUrl::StrictMode ) ),
          ncal_interval( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#interval", QUrl::StrictMode ) ),
          ncal_involvedContact( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#involvedContact", QUrl::StrictMode ) ),
          ncal_journalStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#journalStatus", QUrl::StrictMode ) ),
          ncal_lastModified( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#lastModified", QUrl::StrictMode ) ),
          ncal_location( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#location", QUrl::StrictMode ) ),
          ncal_locationAltRep( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#locationAltRep", QUrl::StrictMode ) ),
          ncal_member( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#member", QUrl::StrictMode ) ),
          ncal_method( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#method", QUrl::StrictMode ) ),
          ncal_minutely( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#minutely", QUrl::StrictMode ) ),
          ncal_monday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#monday", QUrl::StrictMode ) ),
          ncal_monthly( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#monthly", QUrl::StrictMode ) ),
          ncal_ncalRelation( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#ncalRelation", QUrl::StrictMode ) ),
          ncal_ncalTimezone( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#ncalTimezone", QUrl::StrictMode ) ),
          ncal_needsActionParticipationStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#needsActionParticipationStatus", QUrl::StrictMode ) ),
          ncal_needsActionStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#needsActionStatus", QUrl::StrictMode ) ),
          ncal_nonParticipantRole( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#nonParticipantRole", QUrl::StrictMode ) ),
          ncal_opaqueTransparency( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#opaqueTransparency", QUrl::StrictMode ) ),
          ncal_optParticipantRole( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#optParticipantRole", QUrl::StrictMode ) ),
          ncal_organizer( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#organizer", QUrl::StrictMode ) ),
          ncal_partstat( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#partstat", QUrl::StrictMode ) ),
          ncal_percentComplete( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#percentComplete", QUrl::StrictMode ) ),
          ncal_periodBegin( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#periodBegin", QUrl::StrictMode ) ),
          ncal_periodDuration( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#periodDuration", QUrl::StrictMode ) ),
          ncal_periodEnd( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#periodEnd", QUrl::StrictMode ) ),
          ncal_priority( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#priority", QUrl::StrictMode ) ),
          ncal_privateClassification( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#privateClassification", QUrl::StrictMode ) ),
          ncal_procedureAction( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#procedureAction", QUrl::StrictMode ) ),
          ncal_prodid( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#prodid", QUrl::StrictMode ) ),
          ncal_publicClassification( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#publicClassification", QUrl::StrictMode ) ),
          ncal_range( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#range", QUrl::StrictMode ) ),
          ncal_rdate( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#rdate", QUrl::StrictMode ) ),
          ncal_recurrenceId( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#recurrenceId", QUrl::StrictMode ) ),
          ncal_recurrenceIdDateTime( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#recurrenceIdDateTime", QUrl::StrictMode ) ),
          ncal_related( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#related", QUrl::StrictMode ) ),
          ncal_relatedToChild( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#relatedToChild", QUrl::StrictMode ) ),
          ncal_relatedToParent( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#relatedToParent", QUrl::StrictMode ) ),
          ncal_relatedToSibling( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#relatedToSibling", QUrl::StrictMode ) ),
          ncal_repeat( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#repeat", QUrl::StrictMode ) ),
          ncal_reqParticipantRole( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#reqParticipantRole", QUrl::StrictMode ) ),
          ncal_requestStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#requestStatus", QUrl::StrictMode ) ),
          ncal_requestStatusData( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#requestStatusData", QUrl::StrictMode ) ),
          ncal_resourceUserType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#resourceUserType", QUrl::StrictMode ) ),
          ncal_resources( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#resources", QUrl::StrictMode ) ),
          ncal_resourcesAltRep( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#resourcesAltRep", QUrl::StrictMode ) ),
          ncal_returnStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#returnStatus", QUrl::StrictMode ) ),
          ncal_role( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#role", QUrl::StrictMode ) ),
          ncal_roomUserType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#roomUserType", QUrl::StrictMode ) ),
          ncal_rrule( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#rrule", QUrl::StrictMode ) ),
          ncal_rsvp( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#rsvp", QUrl::StrictMode ) ),
          ncal_saturday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#saturday", QUrl::StrictMode ) ),
          ncal_secondly( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#secondly", QUrl::StrictMode ) ),
          ncal_sentBy( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#sentBy", QUrl::StrictMode ) ),
          ncal_sequence( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#sequence", QUrl::StrictMode ) ),
          ncal_standard( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#standard", QUrl::StrictMode ) ),
          ncal_startTriggerRelation( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#startTriggerRelation", QUrl::StrictMode ) ),
          ncal_statusDescription( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#statusDescription", QUrl::StrictMode ) ),
          ncal_summary( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#summary", QUrl::StrictMode ) ),
          ncal_summaryAltRep( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#summaryAltRep", QUrl::StrictMode ) ),
          ncal_sunday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#sunday", QUrl::StrictMode ) ),
          ncal_tentativeParticipationStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#tentativeParticipationStatus", QUrl::StrictMode ) ),
          ncal_tentativeStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#tentativeStatus", QUrl::StrictMode ) ),
          ncal_thisAndFutureRange( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#thisAndFutureRange", QUrl::StrictMode ) ),
          ncal_thisAndPriorRange( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#thisAndPriorRange", QUrl::StrictMode ) ),
          ncal_thursday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#thursday", QUrl::StrictMode ) ),
          ncal_todoStatus( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#todoStatus", QUrl::StrictMode ) ),
          ncal_transp( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#transp", QUrl::StrictMode ) ),
          ncal_transparentTransparency( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#transparentTransparency", QUrl::StrictMode ) ),
          ncal_trigger( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#trigger", QUrl::StrictMode ) ),
          ncal_triggerDateTime( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#triggerDateTime", QUrl::StrictMode ) ),
          ncal_triggerDuration( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#triggerDuration", QUrl::StrictMode ) ),
          ncal_tuesday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#tuesday", QUrl::StrictMode ) ),
          ncal_tzid( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#tzid", QUrl::StrictMode ) ),
          ncal_tzname( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#tzname", QUrl::StrictMode ) ),
          ncal_tzoffsetfrom( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#tzoffsetfrom", QUrl::StrictMode ) ),
          ncal_tzoffsetto( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#tzoffsetto", QUrl::StrictMode ) ),
          ncal_tzurl( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#tzurl", QUrl::StrictMode ) ),
          ncal_uid( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#uid", QUrl::StrictMode ) ),
          ncal_unknownUserType( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#unknownUserType", QUrl::StrictMode ) ),
          ncal_until( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#until", QUrl::StrictMode ) ),
          ncal_url( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#url", QUrl::StrictMode ) ),
          ncal_version( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#version", QUrl::StrictMode ) ),
          ncal_wednesday( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#wednesday", QUrl::StrictMode ) ),
          ncal_weekly( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#weekly", QUrl::StrictMode ) ),
          ncal_wkst( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#wkst", QUrl::StrictMode ) ),
          ncal_yearly( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#yearly", QUrl::StrictMode ) ) {
    }

    QUrl ncal_namespace;
    QUrl ncal_AccessClassification;
    QUrl ncal_Alarm;
    QUrl ncal_AlarmAction;
    QUrl ncal_Attachment;
    QUrl ncal_AttachmentEncoding;
    QUrl ncal_Attendee;
    QUrl ncal_AttendeeOrOrganizer;
    QUrl ncal_AttendeeRole;
    QUrl ncal_BydayRulePart;
    QUrl ncal_Calendar;
    QUrl ncal_CalendarDataObject;
    QUrl ncal_CalendarScale;
    QUrl ncal_CalendarUserType;
    QUrl ncal_Event;
    QUrl ncal_EventStatus;
    QUrl ncal_Freebusy;
    QUrl ncal_FreebusyPeriod;
    QUrl ncal_FreebusyType;
    QUrl ncal_Journal;
    QUrl ncal_JournalStatus;
    QUrl ncal_NcalDateTime;
    QUrl ncal_NcalPeriod;
    QUrl ncal_NcalTimeEntity;
    QUrl ncal_Organizer;
    QUrl ncal_ParticipationStatus;
    QUrl ncal_RecurrenceFrequency;
    QUrl ncal_RecurrenceIdentifier;
    QUrl ncal_RecurrenceIdentifierRange;
    QUrl ncal_RecurrenceRule;
    QUrl ncal_RequestStatus;
    QUrl ncal_TimeTransparency;
    QUrl ncal_Timezone;
    QUrl ncal_TimezoneObservance;
    QUrl ncal_Todo;
    QUrl ncal_TodoStatus;
    QUrl ncal_Trigger;
    QUrl ncal_TriggerRelation;
    QUrl ncal_UnionOfAlarmEventFreebusyJournalTodo;
    QUrl ncal_UnionOfAlarmEventFreebusyTodo;
    QUrl ncal_UnionOfAlarmEventJournalTodo;
    QUrl ncal_UnionOfAlarmEventTodo;
    QUrl ncal_UnionOfEventFreebusy;
    QUrl ncal_UnionOfEventFreebusyJournalTodo;
    QUrl ncal_UnionOfEventJournalTimezoneTodo;
    QUrl ncal_UnionOfEventJournalTodo;
    QUrl ncal_UnionOfEventTodo;
    QUrl ncal_UnionOfTimezoneObservanceEventFreebusyJournalTimezoneTodo;
    QUrl ncal_UnionOfTimezoneObservanceEventFreebusyTimezoneTodo;
    QUrl ncal_UnionOfTimezoneObservanceEventJournalTimezoneTodo;
    QUrl ncal_UnionParentClass;
    QUrl ncal_Weekday;
    QUrl ncal__8bitEncoding;
    QUrl ncal_acceptedParticipationStatus;
    QUrl ncal_action;
    QUrl ncal_attach;
    QUrl ncal_attachmentContent;
    QUrl ncal_attachmentUri;
    QUrl ncal_attendee;
    QUrl ncal_audioAction;
    QUrl ncal_base64Encoding;
    QUrl ncal_busyFreebusyType;
    QUrl ncal_busyTentativeFreebusyType;
    QUrl ncal_busyUnavailableFreebusyType;
    QUrl ncal_byday;
    QUrl ncal_bydayModifier;
    QUrl ncal_bydayWeekday;
    QUrl ncal_byhour;
    QUrl ncal_byminute;
    QUrl ncal_bymonth;
    QUrl ncal_bymonthday;
    QUrl ncal_bysecond;
    QUrl ncal_bysetpos;
    QUrl ncal_byweekno;
    QUrl ncal_byyearday;
    QUrl ncal_calscale;
    QUrl ncal_cancelledEventStatus;
    QUrl ncal_cancelledJournalStatus;
    QUrl ncal_cancelledTodoStatus;
    QUrl ncal_categories;
    QUrl ncal_chairRole;
    QUrl ncal_class;
    QUrl ncal_comment;
    QUrl ncal_commentAltRep;
    QUrl ncal_completed;
    QUrl ncal_completedParticipationStatus;
    QUrl ncal_completedStatus;
    QUrl ncal_component;
    QUrl ncal_confidentialClassification;
    QUrl ncal_confirmedStatus;
    QUrl ncal_contact;
    QUrl ncal_contactAltRep;
    QUrl ncal_count;
    QUrl ncal_created;
    QUrl ncal_cutype;
    QUrl ncal_daily;
    QUrl ncal_date;
    QUrl ncal_dateTime;
    QUrl ncal_daylight;
    QUrl ncal_declinedParticipationStatus;
    QUrl ncal_delegatedFrom;
    QUrl ncal_delegatedParticipationStatus;
    QUrl ncal_delegatedTo;
    QUrl ncal_description;
    QUrl ncal_descriptionAltRep;
    QUrl ncal_dir;
    QUrl ncal_displayAction;
    QUrl ncal_draftStatus;
    QUrl ncal_dtend;
    QUrl ncal_dtstamp;
    QUrl ncal_dtstart;
    QUrl ncal_due;
    QUrl ncal_duration;
    QUrl ncal_emailAction;
    QUrl ncal_encoding;
    QUrl ncal_endTriggerRelation;
    QUrl ncal_eventStatus;
    QUrl ncal_exdate;
    QUrl ncal_exrule;
    QUrl ncal_fbtype;
    QUrl ncal_finalStatus;
    QUrl ncal_fmttype;
    QUrl ncal_freeFreebusyType;
    QUrl ncal_freebusy;
    QUrl ncal_freq;
    QUrl ncal_friday;
    QUrl ncal_geo;
    QUrl ncal_gregorianCalendarScale;
    QUrl ncal_groupUserType;
    QUrl ncal_hasAlarm;
    QUrl ncal_hourly;
    QUrl ncal_inProcessParticipationStatus;
    QUrl ncal_inProcessStatus;
    QUrl ncal_individualUserType;
    QUrl ncal_interval;
    QUrl ncal_involvedContact;
    QUrl ncal_journalStatus;
    QUrl ncal_lastModified;
    QUrl ncal_location;
    QUrl ncal_locationAltRep;
    QUrl ncal_member;
    QUrl ncal_method;
    QUrl ncal_minutely;
    QUrl ncal_monday;
    QUrl ncal_monthly;
    QUrl ncal_ncalRelation;
    QUrl ncal_ncalTimezone;
    QUrl ncal_needsActionParticipationStatus;
    QUrl ncal_needsActionStatus;
    QUrl ncal_nonParticipantRole;
    QUrl ncal_opaqueTransparency;
    QUrl ncal_optParticipantRole;
    QUrl ncal_organizer;
    QUrl ncal_partstat;
    QUrl ncal_percentComplete;
    QUrl ncal_periodBegin;
    QUrl ncal_periodDuration;
    QUrl ncal_periodEnd;
    QUrl ncal_priority;
    QUrl ncal_privateClassification;
    QUrl ncal_procedureAction;
    QUrl ncal_prodid;
    QUrl ncal_publicClassification;
    QUrl ncal_range;
    QUrl ncal_rdate;
    QUrl ncal_recurrenceId;
    QUrl ncal_recurrenceIdDateTime;
    QUrl ncal_related;
    QUrl ncal_relatedToChild;
    QUrl ncal_relatedToParent;
    QUrl ncal_relatedToSibling;
    QUrl ncal_repeat;
    QUrl ncal_reqParticipantRole;
    QUrl ncal_requestStatus;
    QUrl ncal_requestStatusData;
    QUrl ncal_resourceUserType;
    QUrl ncal_resources;
    QUrl ncal_resourcesAltRep;
    QUrl ncal_returnStatus;
    QUrl ncal_role;
    QUrl ncal_roomUserType;
    QUrl ncal_rrule;
    QUrl ncal_rsvp;
    QUrl ncal_saturday;
    QUrl ncal_secondly;
    QUrl ncal_sentBy;
    QUrl ncal_sequence;
    QUrl ncal_standard;
    QUrl ncal_startTriggerRelation;
    QUrl ncal_statusDescription;
    QUrl ncal_summary;
    QUrl ncal_summaryAltRep;
    QUrl ncal_sunday;
    QUrl ncal_tentativeParticipationStatus;
    QUrl ncal_tentativeStatus;
    QUrl ncal_thisAndFutureRange;
    QUrl ncal_thisAndPriorRange;
    QUrl ncal_thursday;
    QUrl ncal_todoStatus;
    QUrl ncal_transp;
    QUrl ncal_transparentTransparency;
    QUrl ncal_trigger;
    QUrl ncal_triggerDateTime;
    QUrl ncal_triggerDuration;
    QUrl ncal_tuesday;
    QUrl ncal_tzid;
    QUrl ncal_tzname;
    QUrl ncal_tzoffsetfrom;
    QUrl ncal_tzoffsetto;
    QUrl ncal_tzurl;
    QUrl ncal_uid;
    QUrl ncal_unknownUserType;
    QUrl ncal_until;
    QUrl ncal_url;
    QUrl ncal_version;
    QUrl ncal_wednesday;
    QUrl ncal_weekly;
    QUrl ncal_wkst;
    QUrl ncal_yearly;
};

Q_GLOBAL_STATIC( NcalPrivate, s_ncal )

QUrl Vocabulary::NCAL::ncalNamespace()
{
    return s_ncal()->ncal_namespace;
}

QUrl Vocabulary::NCAL::AccessClassification()
{
    return s_ncal()->ncal_AccessClassification;
}

QUrl Vocabulary::NCAL::Alarm()
{
    return s_ncal()->ncal_Alarm;
}

QUrl Vocabulary::NCAL::AlarmAction()
{
    return s_ncal()->ncal_AlarmAction;
}

QUrl Vocabulary::NCAL::Attachment()
{
    return s_ncal()->ncal_Attachment;
}

QUrl Vocabulary::NCAL::AttachmentEncoding()
{
    return s_ncal()->ncal_AttachmentEncoding;
}

QUrl Vocabulary::NCAL::Attendee()
{
    return s_ncal()->ncal_Attendee;
}

QUrl Vocabulary::NCAL::AttendeeOrOrganizer()
{
    return s_ncal()->ncal_AttendeeOrOrganizer;
}

QUrl Vocabulary::NCAL::AttendeeRole()
{
    return s_ncal()->ncal_AttendeeRole;
}

QUrl Vocabulary::NCAL::BydayRulePart()
{
    return s_ncal()->ncal_BydayRulePart;
}

QUrl Vocabulary::NCAL::Calendar()
{
    return s_ncal()->ncal_Calendar;
}

QUrl Vocabulary::NCAL::CalendarDataObject()
{
    return s_ncal()->ncal_CalendarDataObject;
}

QUrl Vocabulary::NCAL::CalendarScale()
{
    return s_ncal()->ncal_CalendarScale;
}

QUrl Vocabulary::NCAL::CalendarUserType()
{
    return s_ncal()->ncal_CalendarUserType;
}

QUrl Vocabulary::NCAL::Event()
{
    return s_ncal()->ncal_Event;
}

QUrl Vocabulary::NCAL::EventStatus()
{
    return s_ncal()->ncal_EventStatus;
}

QUrl Vocabulary::NCAL::Freebusy()
{
    return s_ncal()->ncal_Freebusy;
}

QUrl Vocabulary::NCAL::FreebusyPeriod()
{
    return s_ncal()->ncal_FreebusyPeriod;
}

QUrl Vocabulary::NCAL::FreebusyType()
{
    return s_ncal()->ncal_FreebusyType;
}

QUrl Vocabulary::NCAL::Journal()
{
    return s_ncal()->ncal_Journal;
}

QUrl Vocabulary::NCAL::JournalStatus()
{
    return s_ncal()->ncal_JournalStatus;
}

QUrl Vocabulary::NCAL::NcalDateTime()
{
    return s_ncal()->ncal_NcalDateTime;
}

QUrl Vocabulary::NCAL::NcalPeriod()
{
    return s_ncal()->ncal_NcalPeriod;
}

QUrl Vocabulary::NCAL::NcalTimeEntity()
{
    return s_ncal()->ncal_NcalTimeEntity;
}

QUrl Vocabulary::NCAL::Organizer()
{
    return s_ncal()->ncal_Organizer;
}

QUrl Vocabulary::NCAL::ParticipationStatus()
{
    return s_ncal()->ncal_ParticipationStatus;
}

QUrl Vocabulary::NCAL::RecurrenceFrequency()
{
    return s_ncal()->ncal_RecurrenceFrequency;
}

QUrl Vocabulary::NCAL::RecurrenceIdentifier()
{
    return s_ncal()->ncal_RecurrenceIdentifier;
}

QUrl Vocabulary::NCAL::RecurrenceIdentifierRange()
{
    return s_ncal()->ncal_RecurrenceIdentifierRange;
}

QUrl Vocabulary::NCAL::RecurrenceRule()
{
    return s_ncal()->ncal_RecurrenceRule;
}

QUrl Vocabulary::NCAL::RequestStatus()
{
    return s_ncal()->ncal_RequestStatus;
}

QUrl Vocabulary::NCAL::TimeTransparency()
{
    return s_ncal()->ncal_TimeTransparency;
}

QUrl Vocabulary::NCAL::Timezone()
{
    return s_ncal()->ncal_Timezone;
}

QUrl Vocabulary::NCAL::TimezoneObservance()
{
    return s_ncal()->ncal_TimezoneObservance;
}

QUrl Vocabulary::NCAL::Todo()
{
    return s_ncal()->ncal_Todo;
}

QUrl Vocabulary::NCAL::TodoStatus()
{
    return s_ncal()->ncal_TodoStatus;
}

QUrl Vocabulary::NCAL::Trigger()
{
    return s_ncal()->ncal_Trigger;
}

QUrl Vocabulary::NCAL::TriggerRelation()
{
    return s_ncal()->ncal_TriggerRelation;
}

QUrl Vocabulary::NCAL::UnionOfAlarmEventFreebusyJournalTodo()
{
    return s_ncal()->ncal_UnionOfAlarmEventFreebusyJournalTodo;
}

QUrl Vocabulary::NCAL::UnionOfAlarmEventFreebusyTodo()
{
    return s_ncal()->ncal_UnionOfAlarmEventFreebusyTodo;
}

QUrl Vocabulary::NCAL::UnionOfAlarmEventJournalTodo()
{
    return s_ncal()->ncal_UnionOfAlarmEventJournalTodo;
}

QUrl Vocabulary::NCAL::UnionOfAlarmEventTodo()
{
    return s_ncal()->ncal_UnionOfAlarmEventTodo;
}

QUrl Vocabulary::NCAL::UnionOfEventFreebusy()
{
    return s_ncal()->ncal_UnionOfEventFreebusy;
}

QUrl Vocabulary::NCAL::UnionOfEventFreebusyJournalTodo()
{
    return s_ncal()->ncal_UnionOfEventFreebusyJournalTodo;
}

QUrl Vocabulary::NCAL::UnionOfEventJournalTimezoneTodo()
{
    return s_ncal()->ncal_UnionOfEventJournalTimezoneTodo;
}

QUrl Vocabulary::NCAL::UnionOfEventJournalTodo()
{
    return s_ncal()->ncal_UnionOfEventJournalTodo;
}

QUrl Vocabulary::NCAL::UnionOfEventTodo()
{
    return s_ncal()->ncal_UnionOfEventTodo;
}

QUrl Vocabulary::NCAL::UnionOfTimezoneObservanceEventFreebusyJournalTimezoneTodo()
{
    return s_ncal()->ncal_UnionOfTimezoneObservanceEventFreebusyJournalTimezoneTodo;
}

QUrl Vocabulary::NCAL::UnionOfTimezoneObservanceEventFreebusyTimezoneTodo()
{
    return s_ncal()->ncal_UnionOfTimezoneObservanceEventFreebusyTimezoneTodo;
}

QUrl Vocabulary::NCAL::UnionOfTimezoneObservanceEventJournalTimezoneTodo()
{
    return s_ncal()->ncal_UnionOfTimezoneObservanceEventJournalTimezoneTodo;
}

QUrl Vocabulary::NCAL::UnionParentClass()
{
    return s_ncal()->ncal_UnionParentClass;
}

QUrl Vocabulary::NCAL::Weekday()
{
    return s_ncal()->ncal_Weekday;
}

QUrl Vocabulary::NCAL::_8bitEncoding()
{
    return s_ncal()->ncal__8bitEncoding;
}

QUrl Vocabulary::NCAL::acceptedParticipationStatus()
{
    return s_ncal()->ncal_acceptedParticipationStatus;
}

QUrl Vocabulary::NCAL::action()
{
    return s_ncal()->ncal_action;
}

QUrl Vocabulary::NCAL::attach()
{
    return s_ncal()->ncal_attach;
}

QUrl Vocabulary::NCAL::attachmentContent()
{
    return s_ncal()->ncal_attachmentContent;
}

QUrl Vocabulary::NCAL::attachmentUri()
{
    return s_ncal()->ncal_attachmentUri;
}

QUrl Vocabulary::NCAL::attendee()
{
    return s_ncal()->ncal_attendee;
}

QUrl Vocabulary::NCAL::audioAction()
{
    return s_ncal()->ncal_audioAction;
}

QUrl Vocabulary::NCAL::base64Encoding()
{
    return s_ncal()->ncal_base64Encoding;
}

QUrl Vocabulary::NCAL::busyFreebusyType()
{
    return s_ncal()->ncal_busyFreebusyType;
}

QUrl Vocabulary::NCAL::busyTentativeFreebusyType()
{
    return s_ncal()->ncal_busyTentativeFreebusyType;
}

QUrl Vocabulary::NCAL::busyUnavailableFreebusyType()
{
    return s_ncal()->ncal_busyUnavailableFreebusyType;
}

QUrl Vocabulary::NCAL::byday()
{
    return s_ncal()->ncal_byday;
}

QUrl Vocabulary::NCAL::bydayModifier()
{
    return s_ncal()->ncal_bydayModifier;
}

QUrl Vocabulary::NCAL::bydayWeekday()
{
    return s_ncal()->ncal_bydayWeekday;
}

QUrl Vocabulary::NCAL::byhour()
{
    return s_ncal()->ncal_byhour;
}

QUrl Vocabulary::NCAL::byminute()
{
    return s_ncal()->ncal_byminute;
}

QUrl Vocabulary::NCAL::bymonth()
{
    return s_ncal()->ncal_bymonth;
}

QUrl Vocabulary::NCAL::bymonthday()
{
    return s_ncal()->ncal_bymonthday;
}

QUrl Vocabulary::NCAL::bysecond()
{
    return s_ncal()->ncal_bysecond;
}

QUrl Vocabulary::NCAL::bysetpos()
{
    return s_ncal()->ncal_bysetpos;
}

QUrl Vocabulary::NCAL::byweekno()
{
    return s_ncal()->ncal_byweekno;
}

QUrl Vocabulary::NCAL::byyearday()
{
    return s_ncal()->ncal_byyearday;
}

QUrl Vocabulary::NCAL::calscale()
{
    return s_ncal()->ncal_calscale;
}

QUrl Vocabulary::NCAL::cancelledEventStatus()
{
    return s_ncal()->ncal_cancelledEventStatus;
}

QUrl Vocabulary::NCAL::cancelledJournalStatus()
{
    return s_ncal()->ncal_cancelledJournalStatus;
}

QUrl Vocabulary::NCAL::cancelledTodoStatus()
{
    return s_ncal()->ncal_cancelledTodoStatus;
}

QUrl Vocabulary::NCAL::categories()
{
    return s_ncal()->ncal_categories;
}

QUrl Vocabulary::NCAL::chairRole()
{
    return s_ncal()->ncal_chairRole;
}

QUrl Vocabulary::NCAL::ncalClass()
{
    return s_ncal()->ncal_class;
}

QUrl Vocabulary::NCAL::comment()
{
    return s_ncal()->ncal_comment;
}

QUrl Vocabulary::NCAL::commentAltRep()
{
    return s_ncal()->ncal_commentAltRep;
}

QUrl Vocabulary::NCAL::completed()
{
    return s_ncal()->ncal_completed;
}

QUrl Vocabulary::NCAL::completedParticipationStatus()
{
    return s_ncal()->ncal_completedParticipationStatus;
}

QUrl Vocabulary::NCAL::completedStatus()
{
    return s_ncal()->ncal_completedStatus;
}

QUrl Vocabulary::NCAL::component()
{
    return s_ncal()->ncal_component;
}

QUrl Vocabulary::NCAL::confidentialClassification()
{
    return s_ncal()->ncal_confidentialClassification;
}

QUrl Vocabulary::NCAL::confirmedStatus()
{
    return s_ncal()->ncal_confirmedStatus;
}

QUrl Vocabulary::NCAL::contact()
{
    return s_ncal()->ncal_contact;
}

QUrl Vocabulary::NCAL::contactAltRep()
{
    return s_ncal()->ncal_contactAltRep;
}

QUrl Vocabulary::NCAL::count()
{
    return s_ncal()->ncal_count;
}

QUrl Vocabulary::NCAL::created()
{
    return s_ncal()->ncal_created;
}

QUrl Vocabulary::NCAL::cutype()
{
    return s_ncal()->ncal_cutype;
}

QUrl Vocabulary::NCAL::daily()
{
    return s_ncal()->ncal_daily;
}

QUrl Vocabulary::NCAL::date()
{
    return s_ncal()->ncal_date;
}

QUrl Vocabulary::NCAL::dateTime()
{
    return s_ncal()->ncal_dateTime;
}

QUrl Vocabulary::NCAL::daylight()
{
    return s_ncal()->ncal_daylight;
}

QUrl Vocabulary::NCAL::declinedParticipationStatus()
{
    return s_ncal()->ncal_declinedParticipationStatus;
}

QUrl Vocabulary::NCAL::delegatedFrom()
{
    return s_ncal()->ncal_delegatedFrom;
}

QUrl Vocabulary::NCAL::delegatedParticipationStatus()
{
    return s_ncal()->ncal_delegatedParticipationStatus;
}

QUrl Vocabulary::NCAL::delegatedTo()
{
    return s_ncal()->ncal_delegatedTo;
}

QUrl Vocabulary::NCAL::description()
{
    return s_ncal()->ncal_description;
}

QUrl Vocabulary::NCAL::descriptionAltRep()
{
    return s_ncal()->ncal_descriptionAltRep;
}

QUrl Vocabulary::NCAL::dir()
{
    return s_ncal()->ncal_dir;
}

QUrl Vocabulary::NCAL::displayAction()
{
    return s_ncal()->ncal_displayAction;
}

QUrl Vocabulary::NCAL::draftStatus()
{
    return s_ncal()->ncal_draftStatus;
}

QUrl Vocabulary::NCAL::dtend()
{
    return s_ncal()->ncal_dtend;
}

QUrl Vocabulary::NCAL::dtstamp()
{
    return s_ncal()->ncal_dtstamp;
}

QUrl Vocabulary::NCAL::dtstart()
{
    return s_ncal()->ncal_dtstart;
}

QUrl Vocabulary::NCAL::due()
{
    return s_ncal()->ncal_due;
}

QUrl Vocabulary::NCAL::duration()
{
    return s_ncal()->ncal_duration;
}

QUrl Vocabulary::NCAL::emailAction()
{
    return s_ncal()->ncal_emailAction;
}

QUrl Vocabulary::NCAL::encoding()
{
    return s_ncal()->ncal_encoding;
}

QUrl Vocabulary::NCAL::endTriggerRelation()
{
    return s_ncal()->ncal_endTriggerRelation;
}

QUrl Vocabulary::NCAL::eventStatus()
{
    return s_ncal()->ncal_eventStatus;
}

QUrl Vocabulary::NCAL::exdate()
{
    return s_ncal()->ncal_exdate;
}

QUrl Vocabulary::NCAL::exrule()
{
    return s_ncal()->ncal_exrule;
}

QUrl Vocabulary::NCAL::fbtype()
{
    return s_ncal()->ncal_fbtype;
}

QUrl Vocabulary::NCAL::finalStatus()
{
    return s_ncal()->ncal_finalStatus;
}

QUrl Vocabulary::NCAL::fmttype()
{
    return s_ncal()->ncal_fmttype;
}

QUrl Vocabulary::NCAL::freeFreebusyType()
{
    return s_ncal()->ncal_freeFreebusyType;
}

QUrl Vocabulary::NCAL::freebusy()
{
    return s_ncal()->ncal_freebusy;
}

QUrl Vocabulary::NCAL::freq()
{
    return s_ncal()->ncal_freq;
}

QUrl Vocabulary::NCAL::friday()
{
    return s_ncal()->ncal_friday;
}

QUrl Vocabulary::NCAL::geo()
{
    return s_ncal()->ncal_geo;
}

QUrl Vocabulary::NCAL::gregorianCalendarScale()
{
    return s_ncal()->ncal_gregorianCalendarScale;
}

QUrl Vocabulary::NCAL::groupUserType()
{
    return s_ncal()->ncal_groupUserType;
}

QUrl Vocabulary::NCAL::hasAlarm()
{
    return s_ncal()->ncal_hasAlarm;
}

QUrl Vocabulary::NCAL::hourly()
{
    return s_ncal()->ncal_hourly;
}

QUrl Vocabulary::NCAL::inProcessParticipationStatus()
{
    return s_ncal()->ncal_inProcessParticipationStatus;
}

QUrl Vocabulary::NCAL::inProcessStatus()
{
    return s_ncal()->ncal_inProcessStatus;
}

QUrl Vocabulary::NCAL::individualUserType()
{
    return s_ncal()->ncal_individualUserType;
}

QUrl Vocabulary::NCAL::interval()
{
    return s_ncal()->ncal_interval;
}

QUrl Vocabulary::NCAL::involvedContact()
{
    return s_ncal()->ncal_involvedContact;
}

QUrl Vocabulary::NCAL::journalStatus()
{
    return s_ncal()->ncal_journalStatus;
}

QUrl Vocabulary::NCAL::lastModified()
{
    return s_ncal()->ncal_lastModified;
}

QUrl Vocabulary::NCAL::location()
{
    return s_ncal()->ncal_location;
}

QUrl Vocabulary::NCAL::locationAltRep()
{
    return s_ncal()->ncal_locationAltRep;
}

QUrl Vocabulary::NCAL::member()
{
    return s_ncal()->ncal_member;
}

QUrl Vocabulary::NCAL::method()
{
    return s_ncal()->ncal_method;
}

QUrl Vocabulary::NCAL::minutely()
{
    return s_ncal()->ncal_minutely;
}

QUrl Vocabulary::NCAL::monday()
{
    return s_ncal()->ncal_monday;
}

QUrl Vocabulary::NCAL::monthly()
{
    return s_ncal()->ncal_monthly;
}

QUrl Vocabulary::NCAL::ncalRelation()
{
    return s_ncal()->ncal_ncalRelation;
}

QUrl Vocabulary::NCAL::ncalTimezone()
{
    return s_ncal()->ncal_ncalTimezone;
}

QUrl Vocabulary::NCAL::needsActionParticipationStatus()
{
    return s_ncal()->ncal_needsActionParticipationStatus;
}

QUrl Vocabulary::NCAL::needsActionStatus()
{
    return s_ncal()->ncal_needsActionStatus;
}

QUrl Vocabulary::NCAL::nonParticipantRole()
{
    return s_ncal()->ncal_nonParticipantRole;
}

QUrl Vocabulary::NCAL::opaqueTransparency()
{
    return s_ncal()->ncal_opaqueTransparency;
}

QUrl Vocabulary::NCAL::optParticipantRole()
{
    return s_ncal()->ncal_optParticipantRole;
}

QUrl Vocabulary::NCAL::organizer()
{
    return s_ncal()->ncal_organizer;
}

QUrl Vocabulary::NCAL::partstat()
{
    return s_ncal()->ncal_partstat;
}

QUrl Vocabulary::NCAL::percentComplete()
{
    return s_ncal()->ncal_percentComplete;
}

QUrl Vocabulary::NCAL::periodBegin()
{
    return s_ncal()->ncal_periodBegin;
}

QUrl Vocabulary::NCAL::periodDuration()
{
    return s_ncal()->ncal_periodDuration;
}

QUrl Vocabulary::NCAL::periodEnd()
{
    return s_ncal()->ncal_periodEnd;
}

QUrl Vocabulary::NCAL::priority()
{
    return s_ncal()->ncal_priority;
}

QUrl Vocabulary::NCAL::privateClassification()
{
    return s_ncal()->ncal_privateClassification;
}

QUrl Vocabulary::NCAL::procedureAction()
{
    return s_ncal()->ncal_procedureAction;
}

QUrl Vocabulary::NCAL::prodid()
{
    return s_ncal()->ncal_prodid;
}

QUrl Vocabulary::NCAL::publicClassification()
{
    return s_ncal()->ncal_publicClassification;
}

QUrl Vocabulary::NCAL::range()
{
    return s_ncal()->ncal_range;
}

QUrl Vocabulary::NCAL::rdate()
{
    return s_ncal()->ncal_rdate;
}

QUrl Vocabulary::NCAL::recurrenceId()
{
    return s_ncal()->ncal_recurrenceId;
}

QUrl Vocabulary::NCAL::recurrenceIdDateTime()
{
    return s_ncal()->ncal_recurrenceIdDateTime;
}

QUrl Vocabulary::NCAL::related()
{
    return s_ncal()->ncal_related;
}

QUrl Vocabulary::NCAL::relatedToChild()
{
    return s_ncal()->ncal_relatedToChild;
}

QUrl Vocabulary::NCAL::relatedToParent()
{
    return s_ncal()->ncal_relatedToParent;
}

QUrl Vocabulary::NCAL::relatedToSibling()
{
    return s_ncal()->ncal_relatedToSibling;
}

QUrl Vocabulary::NCAL::repeat()
{
    return s_ncal()->ncal_repeat;
}

QUrl Vocabulary::NCAL::reqParticipantRole()
{
    return s_ncal()->ncal_reqParticipantRole;
}

QUrl Vocabulary::NCAL::requestStatus()
{
    return s_ncal()->ncal_requestStatus;
}

QUrl Vocabulary::NCAL::requestStatusData()
{
    return s_ncal()->ncal_requestStatusData;
}

QUrl Vocabulary::NCAL::resourceUserType()
{
    return s_ncal()->ncal_resourceUserType;
}

QUrl Vocabulary::NCAL::resources()
{
    return s_ncal()->ncal_resources;
}

QUrl Vocabulary::NCAL::resourcesAltRep()
{
    return s_ncal()->ncal_resourcesAltRep;
}

QUrl Vocabulary::NCAL::returnStatus()
{
    return s_ncal()->ncal_returnStatus;
}

QUrl Vocabulary::NCAL::role()
{
    return s_ncal()->ncal_role;
}

QUrl Vocabulary::NCAL::roomUserType()
{
    return s_ncal()->ncal_roomUserType;
}

QUrl Vocabulary::NCAL::rrule()
{
    return s_ncal()->ncal_rrule;
}

QUrl Vocabulary::NCAL::rsvp()
{
    return s_ncal()->ncal_rsvp;
}

QUrl Vocabulary::NCAL::saturday()
{
    return s_ncal()->ncal_saturday;
}

QUrl Vocabulary::NCAL::secondly()
{
    return s_ncal()->ncal_secondly;
}

QUrl Vocabulary::NCAL::sentBy()
{
    return s_ncal()->ncal_sentBy;
}

QUrl Vocabulary::NCAL::sequence()
{
    return s_ncal()->ncal_sequence;
}

QUrl Vocabulary::NCAL::standard()
{
    return s_ncal()->ncal_standard;
}

QUrl Vocabulary::NCAL::startTriggerRelation()
{
    return s_ncal()->ncal_startTriggerRelation;
}

QUrl Vocabulary::NCAL::statusDescription()
{
    return s_ncal()->ncal_statusDescription;
}

QUrl Vocabulary::NCAL::summary()
{
    return s_ncal()->ncal_summary;
}

QUrl Vocabulary::NCAL::summaryAltRep()
{
    return s_ncal()->ncal_summaryAltRep;
}

QUrl Vocabulary::NCAL::sunday()
{
    return s_ncal()->ncal_sunday;
}

QUrl Vocabulary::NCAL::tentativeParticipationStatus()
{
    return s_ncal()->ncal_tentativeParticipationStatus;
}

QUrl Vocabulary::NCAL::tentativeStatus()
{
    return s_ncal()->ncal_tentativeStatus;
}

QUrl Vocabulary::NCAL::thisAndFutureRange()
{
    return s_ncal()->ncal_thisAndFutureRange;
}

QUrl Vocabulary::NCAL::thisAndPriorRange()
{
    return s_ncal()->ncal_thisAndPriorRange;
}

QUrl Vocabulary::NCAL::thursday()
{
    return s_ncal()->ncal_thursday;
}

QUrl Vocabulary::NCAL::todoStatus()
{
    return s_ncal()->ncal_todoStatus;
}

QUrl Vocabulary::NCAL::transp()
{
    return s_ncal()->ncal_transp;
}

QUrl Vocabulary::NCAL::transparentTransparency()
{
    return s_ncal()->ncal_transparentTransparency;
}

QUrl Vocabulary::NCAL::trigger()
{
    return s_ncal()->ncal_trigger;
}

QUrl Vocabulary::NCAL::triggerDateTime()
{
    return s_ncal()->ncal_triggerDateTime;
}

QUrl Vocabulary::NCAL::triggerDuration()
{
    return s_ncal()->ncal_triggerDuration;
}

QUrl Vocabulary::NCAL::tuesday()
{
    return s_ncal()->ncal_tuesday;
}

QUrl Vocabulary::NCAL::tzid()
{
    return s_ncal()->ncal_tzid;
}

QUrl Vocabulary::NCAL::tzname()
{
    return s_ncal()->ncal_tzname;
}

QUrl Vocabulary::NCAL::tzoffsetfrom()
{
    return s_ncal()->ncal_tzoffsetfrom;
}

QUrl Vocabulary::NCAL::tzoffsetto()
{
    return s_ncal()->ncal_tzoffsetto;
}

QUrl Vocabulary::NCAL::tzurl()
{
    return s_ncal()->ncal_tzurl;
}

QUrl Vocabulary::NCAL::uid()
{
    return s_ncal()->ncal_uid;
}

QUrl Vocabulary::NCAL::unknownUserType()
{
    return s_ncal()->ncal_unknownUserType;
}

QUrl Vocabulary::NCAL::until()
{
    return s_ncal()->ncal_until;
}

QUrl Vocabulary::NCAL::url()
{
    return s_ncal()->ncal_url;
}

QUrl Vocabulary::NCAL::version()
{
    return s_ncal()->ncal_version;
}

QUrl Vocabulary::NCAL::wednesday()
{
    return s_ncal()->ncal_wednesday;
}

QUrl Vocabulary::NCAL::weekly()
{
    return s_ncal()->ncal_weekly;
}

QUrl Vocabulary::NCAL::wkst()
{
    return s_ncal()->ncal_wkst;
}

QUrl Vocabulary::NCAL::yearly()
{
    return s_ncal()->ncal_yearly;
}
