# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/knotifyconfig' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/akonadi-notes' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmbox' : '@same'
    'pim/kmime' : '@same'
    'pim/libkdepim': '@same'
    'pim/libkgapi' : '@same'
    'pim/kldap' : '@same'
    'third-party/libkolabxml' : '@stable'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kitemmodels': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/ktextwidgets': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/kholidays': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kdav': '@latest'
    'frameworks/kdoctools': '@latest'
    'third-party/qtkeychain': '@latest'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts' : '@latest-kf6'
    'frameworks/kcalendarcore' : '@latest-kf6'
    'frameworks/knotifyconfig' : '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/akonadi-calendar' : '@latest-kf6'
    'pim/akonadi-contacts' : '@latest-kf6'
    'pim/akonadi-mime' : '@latest-kf6'
    'pim/akonadi-notes' : '@latest-kf6'
    'pim/kcalutils' : '@latest-kf6'
    'pim/kidentitymanagement' : '@latest-kf6'
    'pim/kimap' : '@latest-kf6'
    'pim/kmailtransport' : '@latest-kf6'
    'pim/kmbox' : '@latest-kf6'
    'pim/kmime' : '@latest-kf6'
    'pim/libkdepim': '@latest-kf6'
    'pim/libkgapi' : '@latest-kf6'
    'pim/kldap' : '@latest-kf6'
    'third-party/libkolabxml' : '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kholidays': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kdav': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'third-party/qtkeychain': '@latest-kf6'
