# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcontacts': 'Frameworks/6.24'
    'frameworks/kcalendarcore': 'Frameworks/6.24'
    'frameworks/knotifyconfig': 'Frameworks/6.24'
    'pim/akonadi': '@same'
    'pim/akonadi-calendar': '@same'
    'pim/akonadi-contacts': '@same'
    'pim/akonadi-mime': '@same'
    'pim/kcalutils': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kimap': '@same'
    'pim/kmailtransport': '@same'
    'pim/kmbox': '@same'
    'pim/kmime': '@same'
    'pim/libkgapi': '@same'
    'pim/kldap': '@same'
    'third-party/libkolabxml': '@latest-kf6'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'frameworks/kcodecs': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/kdav': 'Frameworks/6.24'
    'third-party/qtkeychain': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'plasma/plasma-activities': '@latest-kf6'

Options:
 cppcheck-ignore-files:
  - 'src/resources/kolab/'
