# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts' : '@latest-kf6'
    'frameworks/kcalendarcore' : '@latest-kf6'
    'frameworks/knotifyconfig' : '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/akonadi-notes' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmbox' : '@same'
    'pim/kmime' : '@same'
    'pim/libkgapi' : '@same'
    'pim/kldap' : '@same'
    'third-party/libkolabxml' : '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kdav': '@latest-kf6'
    'third-party/qtkeychain': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'
