/*
    SPDX-FileCopyrightText: 2016-2020 Laurent Montel <montel@kde.org>

    SPDX-License-Identifier: LGPL-2.0-or-later
*/

#ifndef NEWMAILNOTIFIERSELECTCOLLECTIONWIDGET_TEST_H
#define NEWMAILNOTIFIERSELECTCOLLECTIONWIDGET_TEST_H

#endif // NEWMAILNOTIFIERSELECTCOLLECTIONWIDGET_TEST_H
