######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 3 13:51:12 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += declarative

# Input
HEADERS += dynamictreemodel.h indexfinder.h mainwindow.h
SOURCES += dynamictreemodel.cpp main.cpp mainwindow.cpp
